### ISSUE TITLE
Provide way to rename mime .xml files

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak-builder#1]
_From @jurf on August 13, 2017 14:17_

So we can stop doing things like:

```
"post-install": [
    "mv /app/share/mime/packages/scribus.xml /app/share/mime/packages/net.scribus.Scribus.xml"
]
```

_Copied from original issue: flatpak/flatpak#958_

**Comment by jurf** [comment]
This would also be great for mimetype icons, which currently have to be renamed manually and the new names have to be added to the xml file.

**Comment by hfiguiere** [comment]
This is much more complex. Renaming the mime .xml files. There is also renaming the icons for these mime type that otherwise don't get exported, but then the icon name should be set in the .xml file to match as this breaks the standard name of mime icons.

**Comment by hfiguiere** [comment]
We could have:

`rename-mime: file.xml`

This would rename the MIME .xml file

and also

`rename-mime-icons: [ icon-name ]`

This would act like rename icon, except it would rename to $FLATPAK_ID.icon-name and then modify the MIME .xml file to set the icon name.

**Comment by hfiguiere** [comment]
My proposed implementation in #567
