### ISSUE TITLE
Would providing an interface for caching packages from another package manager make sense?

### ISSUE THREAD

**Issue by stanfieldr** [flatpak/flatpak-builder#116]
Hi I'm looking into using flatpak for an electron app I built. One of my goals was to decouple electron from my app although after searching doesn't seem like this is possible right now? After thinking about this though, we could actually take it a step further than one npm package. We could actually build an interface type that has method(s) to transform some given package manager format (example npm's package.json or package-lock.json) into what flatpak expects (something like you specify in manifest.json under the modules source)

The main benefit here is deduping the data for the person installing the flatpak. So for example if I install electron 19.34.* when installing atom and skype, then it would only have one electron installed on my system if they both use 19.34.*. This would also keep flatpak-builder decoupled from any specific package manager (for example npm, gems, composer, cargo, etc).

**Comment by TingPing** [comment]
https://github.com/flatpak/flatpak-builder-tools

**Comment by TingPing** [comment]
Anyway files are already de-duplicated if identical, so if Electron installs a file (not a combined binary blob) then it "just works".

**Comment by stanfieldr** [comment]
That looks like exactly what I needed. Thanks
