### ISSUE TITLE
Allow modules with duplicate names if they are identical

### ISSUE THREAD

**Issue by alexander255** [flatpak/flatpak-builder#140]
When spreading a larger set of modules across several files one can currently declare “dependecies” between modules by adding the depended upon module to the `"modules"` key of the depending module. For instance if *module-a* requires *module-b*:

*module-a.json*:

```json
{
    "name": "module-a",
    …
    "modules": [
        "module-b.json"
    ]
}
```

*module-b.json*:

```json
{
    "name": "module-b",
    …
}
```

If we now add a nother module *module-c* that also requires *module-b* things will still work if the app requiring this module only depends on this module:

*module-c.json*:

```json
{
    "name": "module-c",
    …
    "modules": [
        "module-b.json"
    ]
}
```

However if the app using these modules (they'd be in a submodule git repo possibly managed by somebody else), requires both the modules *module-a* and *module-c*, then `flatpak-builder` will fail with an error:

```
Failed to init: Duplicate modules named 'module-b'
```

But since there really only is one *module-b* (but referenced twice), the correct answer should actually be to ignore the second “decleration” of *module-b* and thereby flattening the dependency graph in a way that ensures that *module-b* is definitely built before *module-a* and *module-c* without requiring users/tools to perform this step manually.

**Comment by TingPing** [comment]
One problem with ignoring it is that the second build may not have the same result as the first, as in previous build state can change it.

(Also if ignoring duplicates does happen it should be based on the contents of the entire module not just the name)

**Comment by alexlarsson** [comment]
This is not "dependencies", they are purely textual inclusion, and flatpak has no knowledge of them as dependencies or anything complicated. Each file is just a list of things to build in a specific order. Anything else has wide-rangeing effects on reproducibility due to how the flatpak-builder cache works.

Now, we could safely append the include some prefix for the names in the cache so that the name need only be unique per-file. That may make sense, and would let you build these files, although you would rebuild the dependency twice.

**Comment by alexander255** [comment]
> This is not "dependencies", they are purely textual inclusion, and flatpak has no knowledge of them as dependencies or anything complicated. Each file is just a list of things to build in a specific order. Anything else has wide-rangeing effects on reproducibility due to how the flatpak-builder cache works.

But if a module with identical parameters (including name) has already been built once why even consider building it again? After all its result is “already there”?

I realize that `flatpak-builder`'s `'modules'` field is not really a list of dependencies (otherwise it's name would be different), but it has the important property of *ensure B is available before attempting A* in common with full-fledged dependecies. I'm only asking for the ability to allow for the build of *B* not to immediately preceed the build of *A* if a *B* with identical properties has already been built to satisfy some other module.

> Now, we could safely append the include some prefix for the names in the cache so that the name need only be unique per-file. That may make sense, and would let you build these files, although you would rebuild the dependency twice.

Would this allow the second *build iteration* to be a no-op? – Otherwise that sounds like a waste of resources with possibly unexpected side-effects (including user confusion). See also @TingPing's comment:

> One problem with ignoring it is that the second build may not have the same result as the first, as in previous build state can change it.

^ That kind of problem is not what anybody (including me) is looking forward to debug.

**Comment by alexlarsson** [comment]
Building a module again can easily create a different result, if during the time between them some new dependency has been installed. For example, the runtime uses this to bootstrap fontconfig/harfbuzz, when fontconfig has to be rebuilt again after harfbuzz has been installed.

**Comment by superchalupa** [comment]
It's really odd that this one is closed. Do you have any suggestions on alternative ways to achieve this result?

I have an embedded system. It has >400 individual libraries. I am putting everything into flatpaks and will end up with a several dozen flatpaks. We have DOZENS of instances of this exact issue in our build system. Low level libraries that are included in slightly higher level libraries that are then included into even higher level libraries and finally the applications.

Without this feature there is literally NO SANE WAY to organize the build!

Meaning: I have to recursively unpack every single dependency of my applications to make a single flat list.

This is simply unmaintainable. The application authors should not need to know or care that a dependency of a dependency of a dependency has changed. (OR WORSE: a library drops a dependency but the application authors dont remove it, leading to unneeded bloat).

The next issue is that to build successfully, the packages need to be ordered correctly. A single, flat list in every application flatpak manifest, that lists every dependency of every dependency, and orders everything correctly to build. Ugh. This is going to REALLY SUCK.

I DO NOT CARE about the phantom "what if the build produces different output when run again". That literally cannot happen in my build system, and it seems like *vastly* the lesser of evils.

**Comment by superchalupa** [comment]
And to elaborate on the lesser of evils comment:

we "solved" an issue identical to your fontconfig/harfbuzz example by simply having a fontconfig-bootstrap package, then a harfbuzz package that depends on fontconfig-bootstrap, then fontconfig depends on harfbuzz. All the bootstrap files go into a devel package that is never installed.

In other words, if you have the "dependency install changes the build output" issue, there are readily available ways to solve that. But without this feature, there is literally no way for me to actually move my entire system to flatpak like i'd like to.

**Comment by superchalupa** [comment]
And the suggestion to 'add a prefix' is silly and will get me tarred and feathered.

As an example: (names changed to protect IP)

liblowlevel - used by literally everything
libmidlevelA - libmidlevelZ - dozens of libraries that all include liblowlevel
libhighlevelA - libhighlevelZ - dozens of librarires that use various combinations of libmidlevelA-Z and liblowlevel
application - mostly uses libhighlevel libraries, some libmidlevel

with the prefix solution, I'm recompiling liblowlevel dozens of times. Increasing the build times exponentially.
