### ISSUE TITLE
OpenJDK fails to build on CentOS/RHEL machine

### ISSUE THREAD

**Issue by mbooth101** [flatpak/flatpak-builder#160]
OpenJDK seems to fail if it happens to be unlucky and picks a CentOS builder:

https://flathub.org/builds/#/builders/26/builds/254
https://flathub.org/builds/#/builders/29/builds/256 

There is an interesting part in the log:

    /usr/bin/bash: /dev/fd/62: No such file or directory

There seems to be a difference in the contents of /dev between RHEL and Fedora:

When building on Fedora:

    Running: ls -l /dev
    total 0
    crw--w---- 1 mbooth    nfsnobody 136, 10 Jun  4 14:50 console
    lrwxrwxrwx 1 mbooth    mbooth         11 Jun  4 14:50 core -> /proc/kcore
    lrwxrwxrwx 1 mbooth    mbooth         13 Jun  4 14:50 fd -> /proc/self/fd
    crw-rw-rw- 1 nfsnobody nfsnobody   1,  7 May 14 11:06 full
    .... snip ....

When building on RHEL:

    Running: ls -al /dev/
    total 0
    drwxr-xr-x  4 mbooth mbooth    300 Jun  4 14:47 .
    drwxr-xr-x 12 mbooth mbooth    340 Jun  4 14:47 ..
    crw--w----  1 mbooth      5 136, 0 Jun  4 14:47 console
    crw-rw-rw-  1      0      0   1, 7 Jun  4 14:11 full
    .... snip ....

Notice how on Fedora, there is a symlink: `/dev/fd -> /proc/self/fd`

I tried to work around this issue by adding the symlink myself during the build, but that had no effect when I tried it on RHEL:

    Running: ls -al /dev/
    total 0
    drwxr-xr-x  4 mbooth mbooth    300 Jun  4 15:02 .
    drwxr-xr-x 12 mbooth mbooth    340 Jun  4 15:02 ..
    crw--w----  1 mbooth      5 136, 0 Jun  4 15:02 console
    crw-rw-rw-  1      0      0   1, 7 Jun  4 14:11 full
    .... snip ....
    Running: ln -s /proc/self/fd /dev/fd
    Running: ls -al /dev/
    total 0
    drwxr-xr-x  4 mbooth mbooth    300 Jun  4 15:02 .
    drwxr-xr-x 12 mbooth mbooth    340 Jun  4 15:02 ..
    crw--w----  1 mbooth      5 136, 0 Jun  4 15:02 console
    crw-rw-rw-  1      0      0   1, 7 Jun  4 14:11 full
    .... snip ....

On the RHEL build machine, this symlink is present, I can see it:

    $ ls -l /dev/fd
    lrwxrwxrwx. 1 root root 13 Jun  4 14:11 /dev/fd -> /proc/self/fd

But it is no present in the `/dev` when flatpak is building my app.

**Comment by mbooth101** [comment]
What machinery is responsible for creating the `/dev` directory in the build sandbox?

**Comment by alexlarsson** [comment]
I think it might be this:
https://github.com/projectatomic/bubblewrap/commit/e98443065f9abc3c5e2ee52320ace88340a33108

**Comment by alexlarsson** [comment]
Maybe we need to bump the system bwrap reqs.

**Comment by mbooth101** [comment]
Aha, I have `bubblewrap-0.1.8-1.el7.centos.x86_64` from amigadave's COPR repo and on Fedora I have `bubblewrap-0.2.0-3.fc28.x86_64` from the system repo.

**Comment by alexlarsson** [comment]
@mbooth101 sounds like it then. I'll bump the checks in flatpak for next release.

**Comment by alexlarsson** [comment]
We want that anyway for the NFS fixes.

**Comment by mbooth101** [comment]
Can this be considered done? Are the builders updated with the latest flatpak?

**Comment by alexlarsson** [comment]
Yeah, this should be ok now
