### ISSUE TITLE
--install broken

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak-builder#170]
The commit https://github.com/flatpak/flatpak-builder/commit/6d9f874c12ea3e742f15fe014138884da9130e08 is supposed to fix `--install`, but it doesn't:
```
$ flatpak-builder --version
flatpak-builder 0.99.1
$ flatpak-builder --ccache --install --force-clean .app-dir org.example.App.yaml
[...]
Is this ok [y/n]: n
```

**Comment by alexlarsson** [comment]
Nah, that fix is for --install-deps-from= and we need a similiar one for --install
