### ISSUE TITLE
Error parsing yaml manifest with add-extensions

### ISSUE THREAD

**Issue by leamas** [flatpak/flatpak-builder#179]
Attaching a yaml manifest which (unless I made a newbie mistake) should be OK, but gives

    flatpak-builder:10884): Json-CRITICAL **: 13:19:52.328: json_gobject_deserialize: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed
    (flatpak-builder:10884): Json-WARNING **: 13:19:52.328: Failed to deserialize "add-extensions" property of type "gpointer" for an object of type "BuilderManifest"

when fed to package-builder The corresponding json variant seems to work just fine.
flatpak --version: 0.10.4
[org.opencpn.OpenCPN.yaml.gz](https://github.com/flatpak/flatpak-builder/files/2159039/org.opencpn.OpenCPN.yaml.gz)

**Comment by AsavarTzeth** [comment]
At first glance I see you used lists where there should be dictionaries.

A fully working example in YAML:
https://github.com/flathub/com.github.wwmm.pulseeffects/blob/dd6ba5ba6ce24a6cb742bc518361f556107e33f5/com.github.wwmm.pulseeffects.yml#L37

**Comment by fedelibre** [comment]
I'm having the same error. It's hard to debug because the YAML lint says it's Ok.

I have a main .yaml file which contains a list of modules defined in other yaml files.
Here's a dummy example:

```
modules:
  - foo.yaml
  - bar. yaml
```

foo.yaml is a list of modules:

```
- name: foo
  sources:
    -type: archive
     url: blablabla

- name: bar
  sources:
...
```

Please give me some hints. Thanks!

**Comment by refi64** [comment]
Each module file may only contain one module. That one module can have nested modules however, see some of the modules in shared-modules for an example.

**Comment by fedelibre** [comment]
Alright, so my foo.yaml should be written as:

```
name: foo
sources:
  -type: archive
   url: blablabla

modules:
  - name: buzz
  ....
  - name: another
  ...
```
