### ISSUE TITLE
tar jxf and cp -R go crazy

### ISSUE THREAD

**Issue by user5145** [flatpak/flatpak-builder#196]
I tried to learn flatpak and port dofus at the same time and something has happend what I can't understand. It may be my incompetence, but whenever i try to copy adobe sdk 2.6 i get weird logs informing me that cp or tar jxf are compressing my data
https://pastebin.com/tS7rYKm6

If I try to use type:archieve then it happens during a cp command. Of course cp and tar jxf work without sandbox.

that's the module
https://pastebin.com/G8VYjK2L

The code isn't the best there, but that was only for learning purposes so sorry for that
All the code: https://pastebin.com/YPX9LeWK
I build it using flatpak-builder --repo=repo --force-clean build-dir org.flatpak.Hello.json

**Comment by alexlarsson** [comment]
The compression output is not from tar, but from the next step which is stripping and compressing the debug info from the files. Then it fails because its unable to strip a file, maybe it doesn't have write permissions on it?

**Comment by user5145** [comment]
It worked with sudo, thanks. I should try it firstly, but i don't remember building it with root privileges previously so I was sure that it is not possible to be so simple and i didn't know that it creates any debug information inside a working directory, I was only aware of cache.

**Comment by user5145** [comment]
ok. i wasn't able to fully test it because winepak server was down and i wasn't able to update flatpak applications without removing hundreds of gigs of games. So even if it has permission (644 or/and 777), downloads adobeairsdk instead of copying and creates .flatpak-builder and build-dir by itself it's still failing without sudo and gives 
Error: module adobe-air: Child process exited with code 1

with sudo it works, though I think it should work without too (should i reopen the issue?). I can recreate it even in a new folder and with json which consist only this one module.
Of course i wouldn't bother you with stupid sudo, but things get worse.

after I add tar.xz with libraries copied from my system /usr/lib64 the adobe-air module fails. What's surprising for me though is that without this preceding it module with libraries in a tar file it works (with sudo). If it was because of the module with libraries than it would break during building that adobes-libraries module, but it does after (when it want to copy adobe air)and the message now is
Error: module adobe-air: Child process exited with code 139

even if i remove the module with libraries to build the cache and then re enable it it will fail to copy that cache with error code 139

PS that previous tar file from the first post has 644 permissions and i'm the owner so flatpak-builder should be able to copy it.
I use arch and flatpak builder 0.99.3
