### ISSUE TITLE
Add option to create bundle

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak-builder#208]
With `flatpak-builder --install` there is a convenient option to build & install locally. A similar option for creating a bundle (e.g. `flatpak-builder --create-bundle`) could be handy.

Upstreams like to use AppImage to provide beta builds. If they can't/don't want to set up their own flatpak repo (maybe they are used to add binaries to their github releases) , this could make it easier for them to fully embrace flatpak also for this use case.

**Comment by TingPing** [comment]
I don't think it should be a one liner, its a bad workflow. It still only becomes a single extra command for CI.

**Comment by alexlarsson** [comment]
I don't see how such a thing helps with any common "manual" workflow. I.e. like development where you might constantly do tweak, built, install, test cycles. Bundles are typically only generated at some release event, which are rare (and often scripted). Also, bundles are sort of weird in the flatpak desing and while the are sometimes useful we don't want to give them to much visibility.
