### ISSUE TITLE
building of module starts over again instead of continuing from where it disrupted

### ISSUE THREAD

**Issue by trappedinspacetime** [flatpak/flatpak-builder#210]
I accidentally clicked `ctrl+c` while building `flatpak-builder --repo=repo--force-clean build-dir com.github.birros.WebArchives.yml` , when I rerun that command to continue the process, it starts over another instance of the module adding `-2` suffix in cache directory. It took hours to rebuild the module. 
Is it possible to force `flatpak-builder` to resume building of a module from where it disrupts?

**Comment by TingPing** [comment]
It is really hard to get that right, a dirty build dir just isn't reliable. You can use `--ccache` to make complication of c/c++ units cached though.

**Comment by alexlarsson** [comment]
Yeah, it is not realistic to reuse a build tree like that. It *might* work for some makefiles, but not others. Also, it might not generate exactly the same result, which is bad for reproducability.
