### ISSUE TITLE
Broken appdata caching

### ISSUE THREAD

**Issue by plata** [flatpak/flatpak-builder#248]
## Linux distribution and version
Manjaro 18.0 KDE

## Flatpak-builder version
1.0.1

## Description of the problem
I had a wrong release data (in the future) in my appdata.xml. Now I cannot build anymore because "timestamp is in the future". Even deleting the build directory does not help. In general, `build-dir/files/share/appdata/xyz.appdata.xml` doesn't seem to respect changes in the appdata.xml and instead pull some version from a cache (wherever that is located).

## Steps to reproduce
see above

**Comment by alexlarsson** [comment]
Can you try building with --disable-cache once. Also, i think i remember fixing something related to this.

**Comment by alexlarsson** [comment]
Yeah, i think this is fixed by: 
https://github.com/flatpak/flatpak-builder/commit/050e075b81587fd8832333fdfba4e18d49e168e8
But, if you ran into into before you may need to remote .flatpak-builder/cache to fix it once.
