### ISSUE TITLE
deb (ppa:alexlarsson/flatpak) elfutils dependency

### ISSUE THREAD

**Issue by plata** [flatpak/flatpak-builder#261]
Should the .deb depend on elfutils? I had to install it manually to solve 
```
Error: module cabextract: Failed to execute child process "eu-strip" (No such file or directory)
```
see https://travis-ci.com/PhoenicisOrg/phoenicis/jobs/172477901

**Comment by alexlarsson** [comment]
The ppa flatpak-builder recommends "elfutils". Did you ignore that?

**Comment by plata** [comment]
It was an installation in Travis so I didn't see any recommendation.
