### ISSUE TITLE
Missing LZMA / 7z support?

### ISSUE THREAD

**Issue by Pixelnarium** [flatpak/flatpak-builder#275]
I tried to make a manifest with an application ( bsnes from https://byuu.org/ ) that comes as 7zip archive as source package. The problem is that I can't use it since flatpak-builder is unable to decompress 7z archives. Using it as "archive" source says:
`Error: module bsnes: Unknown archive format of '/home/user/FlatPak/flatpak/org.byuu.bsnes/.flatpak-builder/downloads/7b7fa745ce593f9912ce116bdf009cd2e70eb034cd7186264c4abedb87a5da36/bsnes_v107-source.7z'`

Then I found this issue: https://github.com/flatpak/flatpak-builder/issues/25 That said that I should decompress the file in the build commands part. Well 7z is not installed and bsdtar seems to be compiled without LZMA support. `7z: command not found` or `bsdtar: LZMA codec is unsupported`

Using bsdtar on my host system (ArchLinux) is able to decompress the file. https://download.byuu.org/bsnes_v107-source.7z

**Comment by nanonyme** [comment]
A workaround would be to add 7z to your manifest and build it first, I guess.

**Comment by Pixelnarium** [comment]
Yeah, I am already doing this but it is not very pretty and I don't see why flatpak-builder should not know about 7z files. But due to that udev is currently broken there are worse problems right now.

**Comment by kirbyfan64** [comment]
AFAIK the udev in shared-modules is there largely just for compat reasons, it doesn't actually *work*, or at least not well

**Comment by Pixelnarium** [comment]
Yeah but many projects depend on it and if it does not build you can't deliver any updates. I made a pull request to fix the build problem with udev.

Anyways, LZMA/7z support would still be nice.

**Comment by TingPing** [comment]
While you are making PRs it shouldn't be hard to add another archive format to `flatpak-builder` =)

**Comment by smcv** [comment]
7z support appears to have been added in 1.0.10.
