### ISSUE TITLE
flatpak-builder fails to download sources

### ISSUE THREAD

**Issue by afranke** [flatpak/flatpak-builder#279]
This is on an up to date Fedora 29, running GNOME Builder 3.32 from flathub. Automatic retrieval of dependencies of my project ([Fractal](https://gitlab.gnome.org/GNOME/fractal)) fails at the download stage. This machine is behind a corporate proxy, which might be the source of the issue.

```
flatpak build-init --arch=x86_64 /home/franke/.var/app/org.gnome.Builder/cache/gnome-builder/projects/fractal/flatpak/staging/x86_64-master org.gnome.FractalDevel org.gnome.Sdk org.gnome.Platform master
flatpak-builder --arch=x86_64 --ccache --force-clean --state-dir /home/franke/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder --download-only --stop-at=fractal /home/franke/.var/app/org.gnome.Builder/cache/gnome-builder/projects/fractal/flatpak/staging/x86_64-master /home/franke/Projets/fractal/flatpak/org.gnome.Fractal.json
Emptying app dir '/home/franke/.var/app/org.gnome.Builder/cache/gnome-builder/projects/fractal/flatpak/staging/x86_64-master'
Downloading sources
Initialized empty Git repository in /home/franke/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder/git/https_source.puri.sm_Librem5_libhandy.git-JK5TZZ/
fatal: unable to access 'https://source.puri.sm/Librem5/libhandy.git/': Failed to connect to source.puri.sm port 443: Connection refused
Failed to download sources: module libhandy: Le processus fils s’est terminé avec le code 128
```

**Comment by refi64** [comment]
Can you clone the repo in question outside of flatpak-builder? If not, then this isn't really a bug...

**Comment by afranke** [comment]
Yes, I can. It works flawlessly in a regular terminal.

```
$ git clone https://source.puri.sm/Librem5/libhandy.git/
Clonage dans 'libhandy'...
remote: Enumerating objects: 2088, done.
remote: Counting objects: 100% (2088/2088), done.
remote: Compressing objects: 100% (948/948), done.
remote: Total 2088 (delta 1355), reused 1720 (delta 1087)
Réception d'objets: 100% (2088/2088), 499.48 KiB | 9.99 MiB/s, fait.
Résolution des deltas: 100% (1355/1355), fait.
```

**Comment by alexlarsson** [comment]
This is a bit weird though, because flatpak doesn't run git in a sandbox. It runs the host git...

Do you have like a proxy env var or something set to make it work?

**Comment by alexlarsson** [comment]
If you run flatpak-builder with -v it will tell you exactly what commandlines it tries to run.

**Comment by afranke** [comment]
> This is a bit weird though, because flatpak doesn't run git in a sandbox. It runs the host git...

This is the flatpak-builder that comes with GNOME Builder though. I don’t have it “on my system”.

> Do you have like a proxy env var or something set to make it work?

I have set up the proxy in two places: first in GNOME Settings, then in my `.bashrc` I do
```
export {http{,s},ftp,rsync,all}_proxy=<proxy_address>
export no_proxy="localhost,127.0.0.0/8,<.corporate.domain.tld>"
```

> If you run flatpak-builder with -v it will tell you exactly what commandlines it tries to run.

I don’t run the command manually, GNOME Builder calls it automatically for me. Is there any way for me to do a manual call with that option, or to add the option to the automatic call?

**Comment by alexlarsson** [comment]
Ah, i see, well in that case git is running in a flatpak sandbox. However, flatpak *does* inherit such env vars from the parent. Maybe the problem is that you launch builder from the shell, which hasn't run .bashrc so it is not set.

Can you try starting builder from a terminal?

**Comment by afranke** [comment]
> Maybe the problem is that you launch builder from the shell, which hasn't run .bashrc so it is not set.

I was suspecting that as well.

> Can you try starting builder from a terminal?

I just tried `flatpak run org.gnome.Builder` from a terminal and it fails the same way.

**Comment by alexlarsson** [comment]
Can you `flatpak run --command=bash org.gnome.Builder` and see what the env is?

**Comment by afranke** [comment]
```
$ LANG=C flatpak run --command=bash org.gnome.Builder
Completions and prompts are unavailable for '/bin/sh'
bash: source: filename argument required
source: usage: source filename [arguments]
```
And then `env|grep -i proxy` shows the variables are set correctly. Running `gnome-builder` from that prompt yields the same git clone problem as above.

**Comment by alexlarsson** [comment]
Hmm, what about running git directly in that prompt?

**Comment by afranke** [comment]
That works as expected.

**Comment by alexlarsson** [comment]
So, seems to be some kind of gnome-builder issue?

**Comment by afranke** [comment]
Should I try `flatpak-builder` in that prompt?

**Comment by alexlarsson** [comment]
Yeah, do that.

**Comment by afranke** [comment]
It complained about the SDK not being installed, but it worked. FWIW I open this issue here after Christian redirected me from https://gitlab.gnome.org/GNOME/gnome-builder/issues/861 (which I guess I can now reopen).

**Comment by bugaevc** [comment]
I have the same problem, also preventing me from cloning libhandy!

I've set up the proxy through GNOME Settings; it's my understanding that it should — ideally — be enough to do that without setting any environment variables manually. That means that either Builder or flatpak-builder need to read the proxy from the settings and export it into an environment variable, or git needs to learn to read the setting in addition to the environment variables.

**Comment by linuxr01** [comment]
I have the same problem.

**Comment by hadess** [comment]
> It complained about the SDK not being installed, but it worked. FWIW I open this issue here after Christian redirected me from https://gitlab.gnome.org/GNOME/gnome-builder/issues/861 (which I guess I can now reopen).

If it fails to clone when inside Builder, it's likely that it's stripping environment variables.

If the problem still happens for you, please file a new bug against GNOME Builder with the debug information that Alex requested that shows that the problem only happens with Builder itself.
