### ISSUE TITLE
Option to allow modules to spawn x11 windows

### ISSUE THREAD

**Issue by dcbaker** [flatpak/flatpak-builder#28]
I'm trying to flatpak a windows application using wine. I can get it to mostly work, but I need to install a few windows dependencies, and while they have a silent install option, they still want to start an x11 window and then immediately close it. I can't really fix that, nor could I fix a windows installer that requires clicking through an installer, but packaging windows applications as flatpaks would be really useful.

**Comment by alexlarsson** [comment]
You can grant x access to the build if you want, but that only then works if you build in an x session, which is not at all guaranteed. In fact most build systems do not have an Xserver running.

**Comment by alexlarsson** [comment]
Maybe you can run a xvfb instance in the build?

**Comment by dcbaker** [comment]
How can I provide X access? I couldn't find it in the documentation. I did try xvfb, but I only took a small pass at it.

**Comment by dcbaker** [comment]
I should add that I can't distribute the flatpak anyway, just the manifest, so requiring that it be built in X shouldn't be a big deal.

**Comment by dcbaker** [comment]
I think (after seeing a comment on a different bug) that this could be done by passing 
`--socket=x11` to the `module:build-options:build-args`, is that correct?

**Comment by dcbaker** [comment]
The answer for anyone else comes searching for this is yes, adding
```json
"build-options: {
  "build-args": ["--socket=x11"]
}
```
to the module that needs x11 is the way to do this.
