### ISSUE TITLE
[RFE] Add quiet mode for sources download

### ISSUE THREAD

**Issue by paulcarroty** [flatpak/flatpak-builder#293]
For some big projects git output can generate megabytes of text, it's not good for readability & CI services with limited log size.

**Comment by refi64** [comment]
When would Git output become megabytes of text? Wouldn't the build logs generally be more of an issue?

I'm not necessarily saying this isn't a problem, but it would probably be better off applying to build logs as well...

-- Ryan
https://refi64.com/

**Comment by paulcarroty** [comment]
https://aomedia.googlesource.com/aom
