### ISSUE TITLE
Sources in separate YAML files aren't parsed

### ISSUE THREAD

**Issue by gasinvein** [flatpak/flatpak-builder#297]
## Linux distribution and version
Fedora 30
## Flatpak-builder version
1.0.7
## Flatpak version
1.4.2
## Description of the problem
Including YAML files with module sources, either with a list or with an object, makes flatpak-builder throw a warning and skip this module. See flathub/com.valvesoftware.Steam#398 for an example, it gives
```
(flatpak-builder:18062): Json-WARNING **: 18:33:52.727: Failed to deserialize "sources" property of type   "gpointer" for an object of type "BuilderModule"
Error parsing modules/gamemode-git.yml: <data>:1:4: Parse error: unexpected identifier `type', expected value
(flatpak-builder:18062): Json-WARNING **: 18:33:52.727: Failed to deserialize "sources" property of type "gpointer" for an object of type "BuilderModule"
```
## Steps to reproduce
1. Create a YAML manifest for an app, add a module to it
2. Put sources of this module into a separate YAML file, add it to the module
3. Try building it

**Comment by gasinvein** [comment]
Here is a test case: https://github.com/gasinvein/flatpak-apps-staging/tree/file.inclusion.TestCase/master
JSON manifest tree builds fine, but YAML does not, neither embedded nor included modules are parsed correctly.

**Comment by refi64** [comment]
I'll make sure to take a look at this tomorrow.
