### ISSUE TITLE
flatpak-builder prepends redundant subdirectory to sources file path

### ISSUE THREAD

**Issue by gasinvein** [flatpak/flatpak-builder#300]
## Linux distribution and version
Fedora 30
## Flatpak-builder version
1.0.8
## Flatpak version
1.4.2
## Description of the problem
It seems like flatpak-builder prepends redundant subdirectory to sources JSON file it there is more than one module with sources in a separate file. If there is only one such module, flatpak-builder parses it fine.
Here is an example: flathub/com.valvesoftware.Steam#404.
Warnings like this appears:
```
Can't open /srv/buildbot/worker/build-x86_64-5/build/sources/sources/ffmpeg-archive.json
(flatpak-builder:18634): Json-WARNING **: 21:12:11.276: Failed to deserialize "sources" property of type "gpointer" for an object of type "BuilderModule"
```
while the sources JSON is in `sources/ffmpeg-archive.json`, not in `sources/sources/ffmpeg-archive.json`.
If we remove all but one (any) module with sources in separate file, it builds, otherwise this issue happens.
This was discovered alongside with #297 
## Steps to reproduce
1. Create an app manifest, add some modules to it
2. Put one module sources into separate file, it builds
3. Put one more module sources into separate file, it throws warning

CC @nanonyme

**Comment by nanonyme** [comment]
Actually this looks like a duplicate of https://github.com/flatpak/flatpak-builder/issues/282

**Comment by gasinvein** [comment]
@nanonyme indeed that one looks similar, closing.
