### ISSUE TITLE
Enhancement: Use a Nightly icon when available

### ISSUE THREAD

**Issue by jimmac** [flatpak/flatpak-builder#304]
We can now easily generate a nightly variant of an application icon for easily distingushing a regular and nightly variants of concurrently installed apps. It would be nice if we would transparently use the nightly variant if a nightly was being built. 

I'll let you figure out the technical details but it would be nice if this happened seamlessly. 

![Screenshot from 2019-09-03 20-16-29](https://user-images.githubusercontent.com/14821/64198059-d1f65780-ce87-11e9-9271-f846b8012d67.png)

![Screenshot from 2019-09-03 20-16-59](https://user-images.githubusercontent.com/14821/64198064-d6227500-ce87-11e9-80b0-98bb772e8b48.png)

**Comment by TingPing** [comment]
Discussed on IRC but this is out of scope of Flatpak really. It doesn't modify icons and has no actual concept of "nightly" apps. The convention is applications rename themselves when built as nightlies and installing a different icon would just be an extension of that.
