### ISSUE TITLE
builder is super slow and writes/reads huge amount of data for no reason

### ISSUE THREAD

**Issue by user5145** [flatpak/flatpak-builder#305]
## Linux distribution and version
fedora 30

## Variables
XDG_DATA_HOME=/home/user5145/Storage/.XDG_DATA
MY_FLATPAK_REPO=/mnt/storage/.flatpak_repo
## fstab
LABEL=LINUX_STORAGE                       /mnt/storage            ext4    defaults,noatime        1 2
/mnt/storage                              /home/user5145/Storage  none    defaults,bind,noatime        1 2

## Flatpak-builder version
1.0.7
## Flatpak version
1.4.2
## Description of the problem
I made my own changes to winepak and ended up having issues with freedesktop.locale which i resolved using this 
`flatpak update --user --subpath= org.freedesktop.Platform.Locale`
(https://github.com/flatpak/flatpak/issues/526) 
but flatpak builder was always slow at building runtimes. Today i discovered that to build forked by me org.winepak.BaseSdk i need at least 50 minutes using i5 6600. The entire project and repo is on HGST 310 (equivalent of wd gold). Builder is always stuck at "Committing stage xyz to cache" and "Exporting org.winepak.BaseSdk to repo", "Exporting org.winepak.BaseSdk.Locale to repo", etc

The important part is that gnome system monitor reports that after i've built org.winepak.BaseSdk and org.winepak.Sdk only 2 times each, bash wrote 198.6Gib to my hdd and has read 42.0Gib but those runtimes are really small like 10 modules in total. To prove that something is wrong i built my version of winepak.Sdk which i forced to crash at ./configure  in the first module and as the screenshots show it wrote 5.5GB before it even started and crashed at 10GB
  
## Steps to reproduce
$ git clone https://gitlab.com/user5145/winepak-sdk-images.git
$ git checkout 19.08
$ cd base-runtime/4.0
$ export MY_FLATPAK_REPO=/mnt/storage/.flatpak_repo
$ flatpak-builder --user --arch=x86_64 --ccache --keep-build-dirs --force-clean --repo=${MY_FLATPAK_REPO} ../../builds/winepak-sdk-images-x86_64 org.winepak.BaseSdk.yml

![Screenshot from 2019-09-05 18-14-52](https://user-images.githubusercontent.com/16629139/64359770-4f95a100-d009-11e9-8fd7-68921e812387.png)

![Screenshot from 2019-09-05 18-24-32](https://user-images.githubusercontent.com/16629139/64360286-756f7580-d00a-11e9-86e4-38c28a92b45b.png)

edit: typo
edit2: other screenshots and i use freedesktop/x86_64/19.08beta
![Screenshot from 2019-09-07 02-18-07](https://user-images.githubusercontent.com/16629139/64467164-5231ec80-d116-11e9-8f17-4f47f6688bb4.png)
![Screenshot from 2019-09-07 02-27-33](https://user-images.githubusercontent.com/16629139/64467235-23684600-d117-11e9-89b0-a49c2c08586b.png)

edit3: sorry, i was wrong. I keep this project on the ssd, but my repo is on the hdd. And I just noticed that .flatapk-builder is a bit big. It has 4,381,019 files and 50GB. It seems weird that something what takes less than 200MB (Mingw. wine, vkd3d) needs a few GB for each run to store cache.
![Screenshot from 2019-09-09 18-52-24](https://user-images.githubusercontent.com/16629139/64551137-b29e7500-d334-11e9-9749-581cbfdabbf5.png)

and is it normal that it takes so long to build runtimes when compared to building apps?

**Comment by alexlarsson** [comment]
Runtimes are pretty large in general, especially the Sdk part and the debug info, and when you're doing a new runtime based on an existing one that starts by extracting the base and then starts working on that. This can be pretty large, although this should only affect things the first time you build it, then it will be used from the cache in the .flatpak-builder dir.

**Comment by user5145** [comment]
i though it's a bug but if this is intended i will have to bear it. Though writing ~7GB of data to disk to even start the compilation reminds me of xserver and how it renders windows that are never shown to the user. Especially that i have 12GB of free ram that want to be filled with data.
