### ISSUE TITLE
flatpak builder fails to find installed extension

### ISSUE THREAD

**Issue by jonathon-love** [flatpak/flatpak-builder#315]
## Linux distribution and version

xenial

## Flatpak-builder version

1.0.1

## Flatpak version

1.0.8

## Description of the problem

flatpak-builder complains about missing extensions, when they are installed

![Screen Shot 2019-10-29 at 11 57 59](https://user-images.githubusercontent.com/3240247/67729297-a5545b80-fa44-11e9-93ad-dfd0ffe6d850.png)

**Comment by refi64** [comment]
Out of curiosity, what happens if you drop the `x86_64/18.08`?

**Comment by jonathon-love** [comment]
same thing (i added the `x86_64/18.08` in to see if that would help it find it):

```
error: Requested extension org.freedesktop.Sdk.Extension.node10 not installed
Error: Child process exited with code 1
```

with thanks

**Comment by jonathon-love** [comment]
ah, if i change `runtime-version` to `18.08` it all works as expected.
