### ISSUE TITLE
[Question] Packaging huge precompiled project

### ISSUE THREAD

**Issue by mantielero** [flatpak/flatpak-builder#326]
I have a doubt about how to pack big precompiled projects (several gigabytes). What I am doing now is putting everything in a `.tar.bz2` file that I reference in sources. Then I use *simple* as *buildsystem*. And copy everything to the `/app` folder.

This involves a lot of physical space, and a lot of time because of the iterative process of creating the manifest.

So two things I need:
1.How to untar everything directly into `/app` instead of creatinf something in `/run/build/module_name`.
2. I manage to copy everything into `/app`, but the install process fails because some issues with permissions that make `eu-strip` to fail. What option could use to start from that point?

Thanks for your help

**Comment by TingPing** [comment]
I don't believe there is any way to bypass that while using `flatpak-builder`. One option is just not using `flatpak-builder`, it is simply a tool to aid in making flatpaks but you can just make a flatpak out of a directory by itself.

**Comment by mantielero** [comment]
Any reference where I can see how to do that?

**Comment by TingPing** [comment]
Hmm, not a ton of docs on it. The starting point is see: `man flatpak-build-init`, `flatpak-build`, and `flatpak-build-finish`

**Comment by mantielero** [comment]
Ok thanks a lot
