### ISSUE TITLE
flatpak-builder cannot find SDK when trying to build example

### ISSUE THREAD

**Issue by schollsky** [flatpak/flatpak-builder#327]
Ubuntu 20.04
Flatpak-builder version 1.09
Flatpak version 1.4.3
Builder cannot find flatpak build environment.

Following tutorial to build example, there's an error - however I installed SDK and runtime lately:

 $ flatpak-builder -v build org.flatpak.firstflat.json 
FB: Running: git config --get user.email
FB: Running: git config --get user.name
FB: Running: flatpak info --arch=x86_64 --show-commit org.freedesktop.Sdk 19.08
error: org.freedesktop.Sdk/x86_64/19.08 not installed
Failed to init: Unable to find sdk org.freedesktop.Sdk version 19.08
stefan@nana:~/Linux/flat$ flatpak repair
Working on the system installation at /var/lib/flatpak
Privileges are required to make changes; assuming --dry-run
Verifying flathub:runtime/org.freedesktop.Platform/x86_64/19.08…
Verifying deploy/runtime/org.freedesktop.Platform.Locale/x86_64/19.08…
Verifying flathub:runtime/org.freedesktop.Platform.openh264/x86_64/19.08…
Verifying deploy/runtime/org.freedesktop.Sdk.Compat.x86_64/x86_64/19.08…
Verifying deploy/runtime/org.freedesktop.Platform.openh264/x86_64/19.08…
Verifying deploy/runtime/org.freedesktop.Platform/x86_64/19.08…
Verifying flathub:runtime/org.freedesktop.Platform.Locale/x86_64/19.08…
Verifying flathub:runtime/org.freedesktop.Sdk.Compat.x86_64/x86_64/19.08…
Verifying deploy/runtime/org.freedesktop.Platform.GL.default/x86_64/19.08…
Verifying flathub:runtime/org.freedesktop.Platform.GL.default/x86_64/19.08…
Verifying flathub:appstream2/x86_64…
stefan@nana:~/Linux/flat$ flatpak-builder -v build org.flatpak.firstflat.json 
FB: Running: git config --get user.email
FB: Running: git config --get user.name
FB: Running: flatpak info --arch=x86_64 --show-commit org.freedesktop.Sdk 19.08
error: org.freedesktop.Sdk/x86_64/19.08 not installed
Failed to init: Unable to find sdk org.freedesktop.Sdk version 19.08

Is there some environment variable to set on my host before starting? Directory "build" is empty as requested by the system, files org.flatpak.firstflat.json and firstflat.sh exist in working directory.

Kind regards

Stefan

**Comment by refi64** [comment]
You need to install the SDK like it says: flatpak install
org.freedesktop.Sdk//19.08

**Comment by TingPing** [comment]
Or add `--install-deps-from=flathub`.
