### ISSUE TITLE
flatpak-builder shouldn't depend on host elfutils

### ISSUE THREAD

**Issue by Anonim19992** [flatpak/flatpak-builder#354]
## Description of the problem

As I understand it, in order to compile a package in it, it is necessary that the necessary collector is on the system itself, for this package (build-essential, pip (not to be confused with pip3)), etc., which helps flatpak-builder package packaging (without build-essential, for example, not installing Anydesk (it will throw an eu-elfcompress error (https://github.com/flathub/com.anydesk.Anydesk/issues/22))) Is it possible to transfer all this to flatpak, so as not to depend on the dependencies (which, in essence, is) the system.

**Comment by TingPing** [comment]
I think the simple answer is we can't rely on every runtime having those tools, and frankly its a very simple dependency that Mint for example already has. I think the only reason you noticed this is because Mint disables Recommended dependencies by default.

**Comment by alexlarsson** [comment]
Yeah, everything that is flatpak-builder calls itself needs to work independent of any particular runtime or whatever version if whatever tool is in that runtime, whereas whatever is called by what is specified by the manifest need only exist in whatever runtime is specified by the manifest.
