### ISSUE TITLE
flatpak-builder --install cannot parse paths that contain utf-8 characters (ex: ă)

### ISSUE THREAD

**Issue by Steinhagen** [flatpak/flatpak-builder#367]
## Linux distribution and version
Fedora 33.20201119.0 (Silverblue)

## Flatpak-builder version
flatpak-builder 1.0.10

## Flatpak version
Flatpak 1.8.3

## Description of the problem
flatpak-builder --install cannot parse paths that contain utf-8 characters (ex: ă).
Example: Muncă -> Munc%C4%83

## Steps to reproduce
```
# flatpak-builder --user --install build org.flatpak.Hello.yml
Emptying app dir 'build'
Downloading sources
Starting build of org.flatpak.Hello
Cache hit for hello, skipping build
Cache hit for cleanup, skipping
Cache hit for finish, skipping
Everything cached, checking out from cache
Exporting org.flatpak.Hello to repo
Commit: a1c4ee3ca4ae2c29f6ee8431f9f36c07b3f6470dd68d59ac8067b26b80d4ec37
Metadata Total: 9
Metadata Written: 1
Content Total: 3
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Installing app/org.flatpak.Hello/x86_64/master
Error: Failed to install org.flatpak.Hello: While pulling app/org.flatpak.Hello/x86_64/master from remote hello1-origin: opening repo: opendir(/home/username/Munc%C4%83/flatpak-test/.flatpak-builder/cache): No such file or directory
```

**Comment by refi64** [comment]
Is this still reproducible? I believe it should be fixed by [this fix](https://github.com/ostreedev/ostree/pull/2293) which is present in OSTree v2021.1.

**Comment by Steinhagen** [comment]
> Is this still reproducible? I believe it should be fixed by [this fix](https://github.com/ostreedev/ostree/pull/2293) which is present in OSTree v2021.1.

It's fixed now.
