### ISSUE TITLE
metainfo.xml: <em> inside <description> fails

### ISSUE THREAD

**Issue by nbenitez** [flatpak/flatpak-builder#371]
Fedora Core 32
Flatpak builder 1.0.10

metainfo [xml spec mentions](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description) you can use `<em>` for emphasis inside `<description>`, I tried to use that for my flathub app description but flatpak-builder fails with the following error:

```
Error loading AppData file: failed to parse /app/share/appdata/net.sourceforge.Pdfedit.appdata.xml: Error on line 13 char 316: <p> already set 'This is legacy software which uses old unmaintained libraries (Qt3, Xpdf 3.02) for which there are no security backports, therefore you should NOT open any untrusted pdf files with this software. Because of this, we have restricted the application to only have access to the standard' and tried to replace with ' and '
Error: ERROR: appstream-compose failed: Child process exited with code 1
```
After removing the `<em>` elements the build runs succesful.

**Comment by TingPing** [comment]
`appstream-compose` is from this project https://github.com/hughsie/appstream-glib

So its either their bug or maybe its outdated on your system.

**Comment by nbenitez** [comment]
Yes, thank you. Duplicate of https://github.com/hughsie/appstream-glib/issues/418
