### ISSUE TITLE
Automatically detect main branch (or default branch)

### ISSUE THREAD

**Issue by A6GibKm** [flatpak/flatpak-builder#375]
## Automatically detect the default branch of a git source

It is becoming more and more common for repositories to name their default branch as main rather than master, and flatpak builder won't find this branch (or any other default master), as only master is hardcoded.

Main could also be hardcoded, or alternatively,  there could be some libgit magic to detect the proper default branch of the repo in question.

**Comment by hadess** [comment]
I was pretty certain I filed that one, but looks like I didn't.

This is how it was done for jhbuild, but the branch is already checked out when that call is made:
https://gitlab.gnome.org/GNOME/jhbuild/-/commit/77192689d33d54a43289130c5d7edf85e89f9f3d

**Comment by refi64** [comment]
So this is actually a bit of a mess, and it turns out *you cannot find this reliably if you're not using `git clone`*. `refs/remotes/origin/HEAD` is only created when you using `git clone`, and it contains the value of the Git internal function `guess_remote_head`. The *only* other section of the Git code where this is used is in `git remote show`, which is a porcelain command and thus cannot be parsed reliably.

**Comment by refi64** [comment]
Amendment: it looks like you *maybe* can obtain it with a mirror repo, but the mechanism for finding it is completely different.

**Comment by hadess** [comment]
That's pretty much how far I got when trying it out as well. I think there there might be a flag day in the not too distant future where the default branch is switched in flatpak-builder and that's that.

**Comment by nbenitez** [comment]
Fortunately, it happens that `git remote show` uses `git ls-remote` underneath to obtain its output, and `git ls-remote` is a plumbing command so it's well suited for scripts.

The remote default branch name can be obtained with:\
`git ls-remote --symref origin HEAD`

I tested it and it's working fine in JHBuild with [this MR I just filed](https://gitlab.gnome.org/GNOME/jhbuild/-/merge_requests/171).

**Comment by hadess** [comment]
> The remote default branch name can be obtained with:
> `git ls-remote --symref origin HEAD`

Huh, you still need the checkout to already be made, which has been the problem from the start.

**Comment by nbenitez** [comment]
Ah yes, but luckily the remote name can also be a URL, so this works:\
`git ls-remote --symref https://gitlab.gnome.org/GNOME/glib.git/ HEAD`

**Comment by hadess** [comment]
> Ah yes, but luckily the remote name can also be a URL, so this works:

Ha, nice!

**Comment by nbenitez** [comment]
I went ahead and submitted PR for this.
