### ISSUE TITLE
Flatpak-builder exited with code 137, but plenty of un-use memory.

### ISSUE THREAD

**Issue by kevinsmia1939** [flatpak/flatpak-builder#389]
Operating System: openSUSE Tumbleweed 20210425
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.11.15-1-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 7.5 GiB of RAM
Swap file: 32 GiB
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

flatpak-builder 1.0.12

Flatpak 1.11.1

I am building Avogadro2 on my local machine.
https://github.com/flathub/org.openchemistry.Avogadro2

I simply fork and clone all the files.
Build with 
`flatpak-builder --install --user build org.openchemistry.Avogadro2 --force-clean`

During python3-numpy module, the error occurred.
```
x86_64-unknown-linux-gnu-gcc: numpy/core/src/umath/ufunc_type_resolution.c
x86_64-unknown-linux-gnu-gcc: numpy/core/src/umath/override.c
x86_64-unknown-linux-gnu-gcc: numpy/core/src/multiarray/mapping.c
x86_64-unknown-linux-gnu-gcc: numpy/core/src/multiarray/methods.c
Error: module python3-numpy: Child process exited with code 137
```

I look around for this code 137 and found that it is cause by not enough memory, which OOM killer kill it.

But I look at htop all the time and memory never exceed 7.5 GiB.

I could build other project that use more memory, but not Avogadro2 for some reason.
I tried deleting .flatpak-builder and build folder, same error.

Why am I getting code 137? Does it mean OOM killer kill flatpak-builder? Why do it got kill when memory is not full?

**Comment by vchernin** [comment]
I have a theory this is somehow linked to using `build-commands` when building a module.

The [Avogadro2 manifest ](https://github.com/flathub/org.openchemistry.Avogadro2) above uses `build-commands` to build some modules.

I have seen this trying to [build PulseEffects](https://github.com/flathub/com.github.wwmm.pulseeffects/pull/53), which used `build-commands` to build `boost`.

And lately in EasyEffects I have found just adding `build-commands` and running `ls` to the EasyEffects module is enough to consistently OOM it. This has never happened building modern versions of EasyEffects before.

@TheEvilSkeleton has also observed this trying to build [Tenacity locally](https://github.com/flathub/flathub/pull/2444#issuecomment-890621546) (also uses `build-commands`).

My system is in no way actually out of memory. For whatever reason, the Flathub builders never seem to have this problem.

On Fedora 34 Silverblue using zram defaults.

**Comment by vchernin** [comment]
Ok apparently this all due to this, nothing to do with `build-commands`: https://github.com/flatpak/xdg-desktop-portal/issues/478

Workaround:
`flatpak permission-reset app-id`
And make sure to click allow when prompted to ask whether your app can run in the background.

I've been testing this briefly and it seems to work.

@kevinsmia1939 does this solve the problem for you?

**Comment by kevinsmia1939** [comment]
> Ok apparently this all due to this, nothing to do with `build-commands`: [flatpak/xdg-desktop-portal#478](https://github.com/flatpak/xdg-desktop-portal/issues/478)
> 
> Workaround:
> `flatpak permission-reset app-id`
> And make sure to click allow when prompted to ask whether your app can run in the background.
> 
> I've been testing this briefly and it seems to work.
> 
> @kevinsmia1939 does this solve the problem for you?

I did not encounter this issue anymore because I change my hardware. So I could not test this again.
I will close this for now, I will revisit this when I got it again.

**Comment by TheJackiMonster** [comment]
> Ok apparently this all due to this, nothing to do with `build-commands`: [flatpak/xdg-desktop-portal#478](https://github.com/flatpak/xdg-desktop-portal/issues/478)
> 
> Workaround: `flatpak permission-reset app-id` And make sure to click allow when prompted to ask whether your app can run in the background.
> 
> I've been testing this briefly and it seems to work.
> 
> @kevinsmia1939 does this solve the problem for you?

I have encountered a similar issue with the current flatpak of [Manuskript](https://github.com/flathub/ch.theologeek.Manuskript):
```
Error: module python3-lxml: Child process exited with code 137
```

The work-around by @vchernin solves the issue but it's a really weird quirk to be honest and I think flatpak-builder should address that. Otherwise more developers will struggle with maintaining their flatpaks.
