### ISSUE TITLE
flatpak-builder 1.0.14 breaks build of org.libreoffice.LibreOffice, empty /run/build/libreoffice

### ISSUE THREAD

**Issue by stbergmann** [flatpak/flatpak-builder#399]
The <https://flathub.org/builds/#/builders/32/builds/50534> flathub build of <https://github.com/flathub/org.libreoffice.LibreOffice/commit/1cd82aaf127545771fb26dda44a6920fd8af4557> "Merge pull request #152 from flathub/lo-7.1.4" suddenly started to fail with `/bin/sh: line 1: ./autogen.sh: No such file or directory`.  A test build at <https://flathub.org/builds/#/builders/32/builds/50954> with a `pwd` and `ls -al` added to the `build-commands` indicated that cwd is an empty `/run/build/libreoffice`.  On `#flatpak:matrix.org`, @barthalion suggested that could be "some fallout from <https://github.com/flatpak/flatpak-builder/releases/tag/1.0.14>".  (And indeed, with a local build of that `flatpak-builder-1.0.14.tar.xz`, I start to get the same error locally too.)

**Comment by alexlarsson** [comment]
Ah, this is due to a change in how it uses dest-filename. It used to (accidentally) allow pathnames in it, now it just allows filenames.
So, instead of:
```
                "dest-filename": "external/tarballs/language-subtag-registry-2021-03-05.tar.bz2"
 ```
Use: 
```
 "dest": "external/tarballs"
 "dest-filename": "language-subtag-registry-2021-03-05.tar.bz2".
```

**Comment by stbergmann** [comment]
Thanks, <https://github.com/flathub/org.libreoffice.LibreOffice/commit/cbcc96c86d78a8489ca3d78d6e0738c854be6913> "Adapt to flatpak-builder 1.0.14 split "dest" + "dest-filename"" appears to help, as <https://flathub.org/builds/#/builders/32/builds/51052> is carrying along now.
But it is probably useful to keep this issue open, so that `flatpak-builder` could produce more helpful error output than silently leaving one puzzled with an empty `/run/build/...` directory?

**Comment by gasinvein** [comment]
> Ah, this is due to a change in how it uses dest-filename. It used to (accidentally) allow pathnames in it, now it just allows filenames.

Maybe it should spit out an error or warning when path is encountered in `dest-filename`?

**Comment by alexlarsson** [comment]
I believe it does print a warning, but that probably drowned in the rest of the build log.

**Comment by gasinvein** [comment]
Indeed, here it is
```
(flatpak-builder:3727851): flatpak-builder-WARNING **: 12:42:52.755: Invalid source: No slashes allowed in dest-filename
(flatpak-builder:3727851): Json-WARNING **: 12:42:52.755: Failed to deserialize "sources" property of type "gpointer" for an object of type "BuilderModule"
```
It was at the very top of the output.

**Comment by stbergmann** [comment]
Any reason that is merely a warning, and not a fatal error?

**Comment by gasinvein** [comment]
@stbergmann I think this is similar to #299

**Comment by nanonyme** [comment]
So should this now be closed if the warnings were fixed to errors?
