### ISSUE TITLE
applications works when built locally, seg faults when built for flathub

### ISSUE THREAD

**Issue by jonathon-love** [flatpak/flatpak-builder#415]
please redirect me if this is the wrong place to post this.

we've been building our app on flathub for a couple of years, and we're currently building against the 19.08 runtime which works fine. however, in migrating to the 20.08 runtime, we've found that our application starts up, but seg faults if you do just about anything. if we build it locally, against the 20.08 runtime, it runs fine. our application has been built across dozens of toolchains, across different OSes over the years, so we're a bit puzzled by this problem. we can only reproduce the issue by building against 20.08 with the flathub builder.

any ideas as to what the issue could be?

this is the problematic PR:

https://github.com/flathub/org.jamovi.jamovi/pull/71

with thanks

**Comment by TingPing** [comment]
What command are you using to build it exactly?

**Comment by refi64** [comment]
The latest build there is working just fine on my end, could it just be the previous one was corrupted or something?

**Comment by jonathon-love** [comment]
> What command are you using to build it exactly?

let me attend @sjentsch to this, as he's been the one building it locally

> The latest build there is working just fine on my end, could it just be the previous one was corrupted or something?

so it will start up, but what happens if you enter some values in the spreadsheet? you'll find that it seg faults then. we've reproduced the issue across three machines.

with thanks

**Comment by sjentsch** [comment]
I used the following commands (line 1: build, line 2: install):
```
flatpak-builder build-dir org.jamovi.jamovi.json
flatpak-builder --user --install --force-clean build-dir org.jamovi.jamovi.json
```
That is, apart from changing the config file, identical to what is in the instructions (https://docs.flatpak.org/en/latest/first-build.html).

Further information for debugging:
```
$ flatpak-builder --version
flatpak-builder 1.0.14

$ flatpak --version
Flatpak 1.11.2

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Comment by jonathon-love** [comment]
just a follow-up here. the same problem occurs when we build against 21.08 on flathub too.

**Comment by jonathon-love** [comment]
hi,

i've been doing some digging on this one ... (the issue arises when building against 20.08 and 21.08, so the retirement of the 19.08 has left us in the awkward position where we can't update our software).

i have since been able to reproduce the issue when building locally, so this isn't flatpak-only as was initially assumed. i've been digging deeper and deeper, and i have to say i'm pretty puzzled.

i've found the strangest behaviour that i don't understand. see the following code:

```
    // these are the assignments, but i don't think they matter, see the cout's below
    long *p;
    p = mm->resolve<long>((long*)0x82100);
    Block ***q;
    q = &(column->blocks);
    
    std::cout << "p points to " << (p) << " and dereferences to " << *p << "\n";
    std::cout << "q points to " << (q) << " and dereferences to " << *q << "\n";
    std::cout << "assigning q to p\n";
    p = (long*)q;
    std::cout << "p points to " << (p) << " and dereferences to " << *p << "\n";
```

this outputs:

```
p points to 0x7f898cc7c100 and dereferences to 0
q points to 0x7f898cc7c100 and dereferences to 0x82158
assigning q to p
p points to 0x7f898cc7c100 and dereferences to 532824
```

as you can see, `p` and `q` point to the same piece of memory, and yet dereference to different values. if i then assign `q` to `p`, then `p` dereferences to the same value as `q`.

could anyone help account for this? it's quite doing my head in. it only occurs when running in the flatpak.

with thanks

**Comment by jonathon-love** [comment]
haha, i kinda needed to do that write-up, and then take a nap ... because it's quite obvious that i need to use the `volatile` keyword here. this has taken me more days than i care to admit.

kind regards
