### ISSUE TITLE
Support for exporting extensions as a single-file bundle

### ISSUE THREAD

**Issue by sgnn7** [flatpak/flatpak-builder#42]
Currently, built extensions are unable to be exported with `build-bundle` since their prefix is not `app` but `runtime` so the refspec can't be found. This is a problem for apps that want to have easily-downloadable and installable extensions.

AC:
- [ ] `flatpak build-bundle` has a way to export an application extension as a single file

**Comment by alexlarsson** [comment]
You can pass --runtime to build-bundle
