### ISSUE TITLE
[Feature request]: Full support for host certs when running under flatpak

### ISSUE THREAD

**Issue by nanonyme** [flatpak/flatpak-builder#443]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

We now have OpenSSL, GnuTLS and NSS integrated with p11kit only to notice curl does something internally to validate certs instead of letting crypto libraries do their thing. This results in p11kit not to be used which means flatpak-builder cannot use host certificates when running under org.flatpak.Builder. Please consider switching all HTTP usage to use libsoup instead which should work as expected.

**Comment by TingPing** [comment]
I believe CURL's main value is `ftp://` support?

**Comment by TingPing** [comment]
I think a reasonable starting point is use libsoup for all http[s] and fallback to curl for everything else.

**Comment by TingPing** [comment]
Oh actually, GIO itself can probably handle FTP, with GFile.

**Comment by mcatanzaro** [comment]
GFile can handle HTTP, too.

**Comment by nanonyme** [comment]
I don't mind alternative solution as long as p11-kit works with that.

**Comment by TingPing** [comment]
> GFile can handle HTTP, too.

Yeah I was wondering if that should be used. I think there is value in using libsoup directly, like it can give you more useful errors, and potentially you can use more features.

I also wonder the security implications of GVFS. Like maybe we don't want to directly expose every protocol it supports but rather a filtered list of protocols like `ftp` that are probably safe. It contains custom things like `admin://` and whatnot.

**Comment by mcatanzaro** [comment]
> I also wonder the security implications of GVFS.

Actually I think it's entirely blocked currently. Surely the sandboxed application won't have permission to access GVFS D-Bus APIs? So we'd need an entirely new portal.

Honestly, I don't think fixing libcurl would be too hard. You just have to find whatever code is sabotaging the trust store, and disable it. Probably won't require writing anything new, because the TLS libraries should work by default if curl would simply not choose a custom trust store on its own.

**Comment by TingPing** [comment]
`flatpak-builder` is a host application.

**Comment by mcatanzaro** [comment]
If so, then it does not care about access to host certs, and this entire issue is pointless. The title of the issue says "when running under flatpak" so I assume that Builder is running it under flatpak.

**Comment by Erick555** [comment]
Yes, there is f-b flatpak: https://github.com/flathub/org.flatpak.Builder

**Comment by nanonyme** [comment]
flatpak-builder works better for atomic workloads where distro doesn't preinstall it (like  Silverblue) as flatpak than host application. Hence it's commonly used like this.

**Comment by nanonyme** [comment]
Installing and updatingflatpak-builder through rpm-ostree requires reboot, installing org.flatpak.Builder does not. Also update flow for flatpak is miles better.

**Comment by Erick555** [comment]
Another usecase for f-b flatpak is LTS distro which doesn't follow upstream updates

**Comment by hfiguiere** [comment]
Just to put into context of the impact this has. If a flaptak package build stuff hosted on mesa.freedesktop.org, flatpak-builder fails on the following configurations:

- RaspberryPi OS Bullseye (it's Debian)
- Flatpak version (from flathub)
- Ubuntu (reported but a user today).

If you use Fedora, installing it with DNF work. If you use Silverblue then you'll have a interrupt your work to reboot after installing if part of the overlay. (still doesn't work in toolbx).

All in all it's a serious problem of a certain number of users.

**Comment by nanonyme** [comment]
I may have figured out how to build curl in a way that it uses crypto backend CA store through https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/6864 so closing this. This should also fix git usage of curl which is super-set of this request.
