### ISSUE TITLE
Unclear failure when icon is invalid path

### ISSUE THREAD

**Issue by christianrauch** [flatpak/flatpak-builder#444]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.0

### Flatpak version

1.12.2

### How to reproduce

1. download the minimal example at https://github.com/christianrauch/flatpak-example
2. build: `./build.sh`

The manifest contains three ways to install the desktop icon. By default the only option that installs the icon properly is active, but it shows a warning during the built. Uncomment the other option to produce errors.

### Expected Behavior

All of the icon install options should work without issues or warnings.

### Actual Behavior

The manifest contains three ways to install the desktop icon:

1. The first option installs to `/app/share/icons/hicolor/apps` without warnings, but the icon will not be visible in an application starter, e.g. in GNOME.
2. The second option installs to `/app/share/icons` with a warning `Icon referenced in desktop file but not exported: org.flatpak.Hello` but the icon will be shown in the starter. This is the only working option. I believe there should be no warning.
3. The third option automatically renamed the icon via `rename-icon: icon1` and also tries to install to `/app/share/icons/hicolor/apps`. But this fails with `Error: icon icon1.svg not found below [...]/files/share/icons`.

### Additional Information

There is not much documentation on how to properly install desktop launcher via flatpak-builder. Some warning messages, like `not exported`, are confusing because the [manifest documentation ](https://docs.flatpak.org/en/latest/manifests.html) does not mention anything about how to control the exported files in the manifest. It is unclear what this warning means and how this can be resolved.

**Comment by TingPing** [comment]
In order to avoid conflicts applications *must* prefix all exported icons with their app-id. So `org.flatpak.Hello.icon1.svg` could be exported but never `icon1.svg`.

**Comment by christianrauch** [comment]
Thanks, the last tip solved the issue. It's just about the path. Installing to `share/icons/hicolor/scalable/apps`:
```yaml
    - install -d /app/share/icons/hicolor/scalable/apps
    - install -m644 icon1.svg /app/share/icons/hicolor/scalable/apps/org.flatpak.Hello.svg
```
correctly installed the icon without a warning.

The documentation you are referring to does not make this explicit. It just proposes to do this: "For example, installing a svg icon in $prefix/share/icons/hicolor/scalable/apps means most desktops will have one icon that works for all sizes.". It's not clear that SVG icons have to be installed in this path for flatpak-builder not to complain. After all, desktops seems to cope with having the SVG at a different location.

If this is an explicit requirement, it should be documented for flatpak-builder.

Prefixing the icon did not solve the problem.

**Comment by TingPing** [comment]
> It's not clear that SVG icons have to be installed in this path for flatpak-builder not to complain

Well. They can be installed to any valid path, like `hicolor/16x16/apps` or `hicolor/32x32/emblems`, etc. It is just an example.

**Comment by TingPing** [comment]
I think the best documentation we have about it is here: https://docs.flatpak.org/en/latest/conventions.html?highlight=icons#application-icons

**Comment by christianrauch** [comment]
> I think the best documentation we have about it is here: https://docs.flatpak.org/en/latest/conventions.html?highlight=icons#application-icons

Oh, so it is there. I missed that part of the documentation. But there are still no examples on how to install icons via the manifest.

> Well. They can be installed to any valid path, like hicolor/16x16/apps, It is just an example.

But if this is just an example and any path within `/app/share/icons` should work, then there should be no warning about missing exports.

**Comment by TingPing** [comment]
> any path within /app/share/icons should work,

No. The spec goes into details but there is a specific layout of subdirectories to work.

I'm not against adding more examples and explanations where-ever it makes sense. If you have recommendations I suggest reporting these to this repo: https://github.com/flatpak/flatpak-docs
