### ISSUE TITLE
[Bug]: make-args do not work for build targets

### ISSUE THREAD

**Issue by Bleuzen** [flatpak/flatpak-builder#445]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.0

### Flatpak version

1.12.2

### How to reproduce

Examples are in my flathub repo. They copy all built files into `${FLATPAK_DEST}/_BUILD` so it is easy to check what got built.

1) Build from a provided example manifest (link below) (command: `flatpak-builder --user --force-clean --install build-dir org.freedesktop.LinuxAudio.Plugins.ChowTapeModel.json`)
2) Look at the files that got built

For example this should build ChowTapeModel with `cmake-ninja` but only the LV2 target:
https://github.com/Bleuzen/flathub/tree/org.freedesktop.LinuxAudio.Plugins.ChowTapeModel-buildtest_cmake-ninja

and as make-args are added and ninja accepts appending build targets as arguments, only the LV2 plugin should get built.
Instead of the expected result, all targets get built (`VST3` and `Standalone` shouldn't be there):
```
❯ ls build-dir/files/_BUILD/Release/
libCHOWTapeModel_SharedCode.a  LV2  Standalone  VST3
```

Same happens when using cmake buildsystem (also should only build LV2):
https://github.com/Bleuzen/flathub/tree/org.freedesktop.LinuxAudio.Plugins.ChowTapeModel-buildtest_cmake

To my understanding, this should use cmake and then make. Make accepts putting build targets as arguments, so should only build the provided targets. But it doesn't in flatpak(-builder).
After a build with the `cmake` buildsystem, again, only LV2 should be built, but all targets got built.

While at the same time, using the following commands does work:
```
cmake -DCMAKE_BUILD_TYPE=Release
make CHOWTapeModel_LV2
```

this does indeed only build the LV2 plugin/target, nothing else.
Afaik this should be the same the `cmake` buildsystem is doing, right?
So seems to me that `make-args` are just not properly appended to make/ninja commands.
Or there are rules / args filters, something like `make-args` have to start with a dash or won't get appended?

### Expected Behavior

We should be able to set build targets in `make-args`

### Actual Behavior

When setting build targets in `make-args` they are ignored and instead the default / all targets are built

**Comment by refi64** [comment]
If I run it with `-v`, I can see it passing the arguments to Ninja:

```
flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/ChowTapeModel --nofilesystem=host --filesystem=/var/home/ryan/collabora/manifests/lv2-test/.flatpak-builder/build/ChowTapeModel-2 --bind-mount=/run/build/ChowTapeModel=/var/home/ryan/collabora/manifests/lv2-test/.flatpak-builder/build/ChowTapeModel-2 --build-dir=/run/build/ChowTapeModel/Plugin --bind-mount=/run/ccache=/var/home/ryan/collabora/manifests/lv2-test/.flatpak-builder/ccache --env=SOURCE_DATE_EPOCH=1641588104 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer  -I/app/extensions/Plugins/ChowTapeModel/include' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/extensions/Plugins/ChowTapeModel/lib/pkgconfig:/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=8 /var/home/ryan/collabora/manifests/lv2-test/.flatpak-builder/rofiles/rofiles-Zuep7S ninja -j8 -l16 CHOWTapeModel_LV2
```

Could it be the `install` step triggering the build of the other parts?

**Comment by Bleuzen** [comment]
@refi64 

> Could it be the `install` step triggering the build of the other parts?

Not sure, could be. Install step isn't needed anyway since it is a plugin and we manually copy the files in place. Is there a way to disable the install step?

**Comment by TingPing** [comment]
`no-make-install: true`

**Comment by Bleuzen** [comment]
> no-make-install: true

This fixed it, so make install was really the problem here, thanks!
