### ISSUE TITLE
Is it possible to continue a disrupted build process?

### ISSUE THREAD

**Issue by kensully** [flatpak/flatpak-builder#46]
First of all thanks a lot for developing such a useful tool.
I was trying to build `vlc` from `https://github.com/flathub/org.videolan.VLC.git` , I cloned the repo and issued the below command 

     flatpak-builder --repo=VLC org.videolan.VLC org.videolan.VLC.json

while building  computer froze and I had to have a reboot after hours of compilation process.

When I rerun the above command I got 

         App dir 'org.videolan.VLC' is not empty. Please delete the existing contents or use --force-clean.
Is there a command switch that I can force to continue building process?

**Comment by TingPing** [comment]
Most of the build state is cached in `.flatpak-builder` so you can safely use `--force-clean` without losing anything important.

**Comment by kensully** [comment]
@TingPing  thank you for the clarification. I checked out the documentation before askingfor help in [this](https://www.mankier.com/1/flatpak-builder#Options) .

It would be time saving if it's documented.

Thank you for helping out.
Regards.
Kenn
