### ISSUE TITLE
[Bug]: flatpak-builder fails to download files over HTTPS

### ISSUE THREAD

**Issue by Jookia** [flatpak/flatpak-builder#468]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

74ae3772e4a270d95e26eec6acfc574a842e621d

### Flatpak version

1.12.7

### How to reproduce

1. Find a flatpak to build that downloads sources
2. Build it using flatpak-builder

### Expected Behavior

The source should download.

### Actual Behavior

```
jookia@jookia-Standard-PC-Q35-ICH9-2009:~/dosbox-x$ ./make-flatpak.sh 
Downloading sources
Downloading https://mesa.freedesktop.org/archive/glu/glu-9.0.2.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    210      0 --:--:-- --:--:-- --:--:--   210
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Failed to download sources: module GLU: server certificate verification failed. CAfile: none CRLfile: none
```

### Additional Information

It looks like this happens if you build flatpak-builder with libcurl4-gnutls-dev instead of libcurl4-openssl-dev. Ubuntu does this, so flatpak-builder is broken out of the box on Ubuntu.

'make check' passes.

**Comment by Jookia** [comment]
Possibly related to https://github.com/flatpak/flatpak/issues/3746

**Comment by Jookia** [comment]
Okay after some more debugging I've found that 'CAfile: none' and 'CRLfile: none' is completely normal for GnuTLS. Curl seems to be working fine. Flatpak-builder can even handle the redirect from https://mesa.freedesktop.org/ !

GnuTLS seems to be failing on the https://archive.mesa3d.org/ certificate.

**Comment by Jookia** [comment]
Looks like GnuTLS really can't deal with some certs:

```
Processed 127 CA certificate(s).
Resolving 'archive.mesa3d.org:443'...
Connecting to '131.252.210.176:443'...
- Certificate type: X.509
- Got a certificate list of 4 certificates.
- Certificate[0] info:
 - subject `CN=archive.mesa3d.org', issuer `CN=R3,O=Let's Encrypt,C=US', serial 0x04b4095290dbfcdf9ea4b9fceb4626e379f7, RSA key 2048 bits, signed using RSA-SHA256, activated `2022-03-05 21:17:47 UTC', expires `2022-06-03 21:17:46 UTC', pin-sha256="TLzRCdKqclpVP5p5QsRnzzjULKRg2t0FA5qPaQ9Ars8="
        Public Key ID:
                sha1:6d6cb1c5e6991c97aacad8a7b4e6f765cc40bfd0
                sha256:4cbcd109d2aa725a553f9a7942c467cf38d42ca460dadd05039a8f690f40aecf
        Public Key PIN:
                pin-sha256:TLzRCdKqclpVP5p5QsRnzzjULKRg2t0FA5qPaQ9Ars8=

- Certificate[1] info:
 - subject `CN=archive.mesa3d.org', issuer `CN=R3,O=Let's Encrypt,C=US', serial 0x04b4095290dbfcdf9ea4b9fceb4626e379f7, RSA key 2048 bits, signed using RSA-SHA256, activated `2022-03-05 21:17:47 UTC', expires `2022-06-03 21:17:46 UTC', pin-sha256="TLzRCdKqclpVP5p5QsRnzzjULKRg2t0FA5qPaQ9Ars8="
- Certificate[2] info:
 - subject `CN=R3,O=Let's Encrypt,C=US', issuer `CN=ISRG Root X1,O=Internet Security Research Group,C=US', serial 0x00912b084acf0c18a753f6d62e25a75f5a, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-09-04 00:00:00 UTC', expires `2025-09-15 16:00:00 UTC', pin-sha256="jQJTbIh0grw0/1TkHSumWb+Fs0Ggogr621gT3PvPKG0="
- Certificate[3] info:
 - subject `CN=ISRG Root X1,O=Internet Security Research Group,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x4001772137d4e942b8ee76aa3c640ab7, RSA key 4096 bits, signed using RSA-SHA256, activated `2021-01-20 19:14:03 UTC', expires `2024-09-30 18:14:03 UTC', pin-sha256="C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M="
- Status: The certificate is NOT trusted. The certificate issuer is unknown. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
```

I have no idea what's happening here, but my workaround solution for now is to just avoid Ubuntu or use the Flatpak builder.

**Comment by Jookia** [comment]
Looks like upstream bug is https://gitlab.com/gnutls/gnutls/-/issues/1357 .

**Comment by Jookia** [comment]
For what it's worth, a workaround might be to set the CA to use p11-kit as --load-ca-certificate="pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust" in gnutls-cli fixes this

**Comment by MehdiChinoune** [comment]
> For what it's worth, a workaround might be to set the CA to use p11-kit as --load-ca-certificate="pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust" or --x509cafile=pkcs11: in gnutls-cli fixes this

Could you show how to apply this workaround

**Comment by Jookia** [comment]
I don't think you can apply it without modifying Flatpak some how- those are just the commands to get gnutls-cli to work.

My current workaround here would be to use a Flatpak version of Flatpak builder or to replace the files in the sources list of the YAML.

**Comment by Jookia** [comment]
Update: This is fixed upstream in GnuTLS: https://gitlab.com/gnutls/gnutls/-/commit/086e9c4e9bb37c0b6badea3ce615e619b3e38fe2

**Comment by Erick555** [comment]
You may try flatpak builder as flatpak to overcome such issues: https://github.com/flathub/org.flatpak.Builder

**Comment by Jookia** [comment]
Yes I did do that. In this case I also changed to a different mirror for a file instead.

**Comment by leuc** [comment]
```patch
diff --git a/glu/glu-9.json b/glu/glu-9.json
index c054749..e0aba90 100644
--- a/glu/glu-9.json
+++ b/glu/glu-9.json
@@ -5,6 +5,9 @@
     {
       "type": "archive",
       "url": "https://archive.mesa3d.org/glu/glu-9.0.2.tar.xz",
+      "mirror-urls": [
+          "ftp://ftp.freedesktop.org/pub/mesa/glu/glu-9.0.2.tar.xz"
+      ],
       "sha256": "6e7280ff585c6a1d9dfcdf2fca489251634b3377bfc33c29e4002466a38d02d4"
     }
   ],
```
