### ISSUE TITLE
RFE: Support sha512 checksum type for archive sources

### ISSUE THREAD

**Issue by mbooth101** [flatpak/flatpak-builder#48]
The project I wish to package as a flatpak app supplies only **sha512** sums for their source downloads and in the flatpak-builder json file, I can only supply **sha256** sums.

It would be neat if flatpak-builder could consume other kinds of checksums.

**Comment by Barthalion** [comment]
I don't really consider checksum as a security measure – it's only about file integrity to me.

**Comment by mbooth101** [comment]
That's right. But upstream supplies only sha512 sums, which means I have to go through the extra step of downloading the source and verifying the sha512 sum before I can locally calculate the sha256 sum to give to flatpak-builder -- I just want to eliminate the need for that extra step :-)

**Comment by Barthalion** [comment]
Right, fair point. Guess `md5` won't hurt either, and I've seen some projects using `sha1` on their websites…

**Comment by mbooth101** [comment]
> Guess md5 won't hurt either

Sure, it might make sense to just allow all the sums supported by glib listed here: https://developer.gnome.org/glib/stable/glib-Data-Checksums.html#GChecksumType

**Comment by mwleeds** [comment]
This feature was added in the 0.10.6 release.
