### ISSUE TITLE
[Bug]: flatpak-builder rejects AppData file that passes appstream-util

### ISSUE THREAD

**Issue by TobTobXX** [flatpak/flatpak-builder#496]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.2

### Flatpak version

1.14.0

### How to reproduce

1. Get (or clone) the manifest and appdata.xml from here: https://git.sr.ht/~tobtobxx/org.example.repro
2. Validate the appdata.xml:
```
$ appstream-util validate-relax org.example.repro.appdata.xml
org.example.repro.appdata.xml: OK
```
3. Try to build the application

### Expected Behavior

It may succeed or fail due to another reason.

### Actual Behavior

```
Processing application org.example.repro
Error loading AppData file: failed to parse /app/share/appdata/org.example.repro.appdata.xml: Error on line 15 char 56: <li> already set ',' and tried to replace with ' and '
Error: ERROR: appstream-compose failed: Child process exited with code 1
```

### Additional Information

`appstream-util --version`: 0.8.1

This may as well be an issue with some appstream library, but flatpak docs tell me it needs to pass `appstream-util validate-relax`. And the issues seen in `validate` (strict) are not related to the `<li>` tags or whatever.

And this also happens when I replace the `<b>` with `<em>` tags.

**Comment by TobTobXX** [comment]
Huh, I just noticed that the bug does not occur when I use `org.freedesktop.Platform` as base. Should I raise the issue on the KDE platform repo?

**Comment by TingPing** [comment]
We use a modified version of the tool that you can install: `flatpak install flathub org.freedesktop.appstream-glib`

**Comment by TobTobXX** [comment]
Good to know, but makes no difference: 
```
~/p/f/org.example.repro > flatpak run org.freedesktop.appstream-glib validate-relax org.example.repro.appdata.xml                                                                         0.155s  (master|?↑1) 21:05
org.example.repro.appdata.xml: OK
```

**Comment by nanonyme** [comment]
This probably needs revisiting now that flatpak-builder has migrated over to libappstream.
