### ISSUE TITLE
[Bug]: git: 'submodule' is not a git command.

### ISSUE THREAD

**Issue by www-cat** [flatpak/flatpak-builder#509]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.3

### Flatpak version

1.14.1

### How to reproduce

1. clone a program that uses modules that use submodules, for example, gnome-builder or gnome-text-editor, they use editorconfig
2. build

### Expected Behavior

- no error
- success

### Actual Behavior

build fails

```
========================================================================
Building module ostree in /home/user/.var/app/org.gnome.Builder/cache/gnome-builder/flatpak-builder/build/ostree-1
========================================================================
Note: switching to 'v2022.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at fbc6d21 Release 2022.2
git: 'submodule' is not a git command. See 'git --help'.
Error: module ostree: Дочірній процес закінчився з кодом 1

```

**Comment by TingPing** [comment]
What is your distro and how did you install `git`?

**Comment by www-cat** [comment]
> What is your distro and how did you install `git`?

debian, apt.
tried guix too, with same result

**Comment by www-cat** [comment]
something in my environment variables sorry
