### ISSUE TITLE
Meson port doesn't support installed-tests

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak-builder#528]
The new meson port doesn't support installed-tests. Meson does not provide any built-in way to do this so it must be done by hand.

See:

https://github.com/flatpak/flatpak-builder/blob/e6ff3de4b15e1f87f1a7d960eed59f0295ef1fb3/tests/Makefile.am.inc
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/359/diffs
https://github.com/mesonbuild/meson/issues/186

**Comment by smcv** [comment]
This is not usually very difficult, and it's a blocker for me packaging 1.3.2 in Debian experimental, so I'll try to propose a PR for this.
