### ISSUE TITLE
[Bug]: Module download fail

### ISSUE THREAD

**Issue by GZYangKui** [flatpak/flatpak-builder#542]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.2

### Flatpak version

1.14.0

### How to reproduce

flatpak-builder --ccache --force-clean --disable-updates --download-only --state-dir=/home/yangkui/work/gtk/.flatpak/flatpak-builder --stop-at=parking-client /home/yangkui/work/gtk/.flatpak/repo /home/yangkui/work/gtk/flatpak/com.qihao.parking.client.json

Downloading sources
Downloading https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.22.1.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Failed to download sources: module libav: gnutls_handshake() failed: Error in the pull function.

### Expected Behavior

Failed to download sources: module libav: gnutls_handshake() failed: Error in the pull function.

### Actual Behavior

Normal download module.

**Comment by TingPing** [comment]
This is likely changed with 1.3.x if you can possibly build it.
