### ISSUE TITLE
[Bug]: cflags property not accepted in module scope

### ISSUE THREAD

**Issue by retiredfeline** [flatpak/flatpak-builder#544]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.2

### Flatpak version

1.12.8

### How to reproduce

Add a cflags property in module scope to the mainfest, like in this fragment describeing a module:

```
    {
      "name": "libnewlib",
      "buildsystem": "autotools",
      "cflags": "-g -Os -D_IEEE_LIBM",
      "config-opts": [
        "--target=ia16-elf",
        "--enable-newlib-elix-level=2",
        "--disable-elks-libc",
        "--disable-freestanding",
        "--disable-newlib-wide-orient",
        "--enable-newlib-nano-malloc",
        "--disable-newlib-multithread",
        "--enable-newlib-global-atexit",
        "--enable-newlib-reent-small",
        "--disable-newlib-fseek-optimization",
        "--disable-newlib-unbuf-stream-opt",
        "--enable-target-optspace",
        "--enable-newlib-io-c99-formats",
        "--enable-newlib-mb",
        "--enable-newlib-iconv",
        "--enable-newlib-iconv-encodings=utf_8,utf_16,cp850,cp852,koi8_uni"
      ],
      "no-autogen": true,
      "sources": [
        {
          "type": "archive",
          "url": "https://launchpad.net/~tkchia/+archive/ubuntu/build-ia16/+sourcefiles/gcc-ia16-elf/libnewlib-ia16-elf_2.4.0-20230316.17-stage1gcc6.3.0-20230311.22-binutils2.39-20221221.21.orig.tar.xz",
          "sha256": "3177a1c4ab7b0952158a8adc2025973c7a5b56f5465247e0cdf1a4c3dc8706dc"
        }
      ]
    }
```

Both flatpak and flatpak-builder give this warning:

(flatpak-builder:11362): flatpak-builder-WARNING **: 23:25:56.005: Unknown property cflags for type BuilderModule

And in fact the CFLAGS in the configuration was not affected.

### Expected Behavior

flatpak-manifest(1) says that cflags can be put in a build or arch section, as well as a module section. Module scope is appropriate as these cflags are only for building this library. So I should see CFLAGS=... being passed to configure.

### Actual Behavior

cflags property is not used at all in a module section. It seems to be unimplemented.

**Comment by Erick555** [comment]
cflags should be specified as sub-option of build-options like this:

```
  "build-options": {
    "cflags": ""-g -Os -D_IEEE_LIBM"
    },

```
See working real-world example: https://github.com/flathub/tv.kodi.Kodi/blob/0ef89fc968419703ba451c3760d3aeadef40d115/addons/imagedecoder.heif/imagedecoder.heif.json#L23-L27

Your current manifest is wrong.

**Comment by retiredfeline** [comment]
Thanks, wish the man page as a bit clearer.

**Comment by smcv** [comment]
> wish the man page was a bit clearer

Please propose a merge request that would have given you the information you needed?

**Comment by retiredfeline** [comment]
Sorry I'm doing just this one project with flatpak and I'm not going to spend time rewriting your documentation. A quick answer might be to add a diagram of the scope hierarchy in the man page. In general my experience of searching how to build a flatpak showed a wide gap between a hello world example and the complex real-world manifests required. I had to get chatgpt to help me understand the procedures, and I have no idea where it dug that that information since searches usually turned up the intro web pages at the top of the hit list.

Thanks and good luck.
