### ISSUE TITLE
Build fails on Fedora: fusermount3 - mount failed

### ISSUE THREAD

**Issue by mijorus** [flatpak/flatpak-builder#571]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.3.5

### Flatpak version

1.15.6

### How to reproduce

1.  Install Fedora 39
2. Install flatpak flatpak-builder
3. Clone https://github.com/mijorus/smile.git (I'm trying to build this one)
4. Install deps and runtimes
5.  Run flatpak-builder build/ it.mijorus.smile.json --user --force-clean

### Expected Behavior

Should build

### Actual Behavior

Build fails

```
flatpak-builder build/ it.mijorus.smile.json --user --force-clean

Emptying app dir 'build/'
Downloading sources
Starting build of it.mijorus.smile
Cache hit for python3-manimpango, skipping build
Cache miss, checking out last cache hit
fusermount3: mount failed: Operation not permitted
========================================================================
Building module python3-dbus-python in /home/lorenzo/Progetti/smile/.flatpak-builder/build/python3-dbus-python-2
========================================================================
Running: pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "dbus-python==1.2.18" --no-build-isolation
error: Build directory /home/lorenzo/Progetti/smile/.flatpak-builder/rofiles/rofiles-FqTtAr not initialized, use flatpak build-init
```

**Comment by mijorus** [comment]
I rebooted my pc, and now it works....weird.

I haven't done anything related to this

**Comment by TingPing** [comment]
Works fine here on Fedora 39.

**Comment by mijorus** [comment]
> Works fine here on Fedora 39.
It works fine here as well, after a reboot.
