### ISSUE TITLE
Latest flatpak-builder tag doesn't build with libglnx submodule

### ISSUE THREAD

**Issue by nanonyme** [flatpak/flatpak-builder#593]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.2

### Flatpak version

1.15.6

### How to reproduce

Build flatpak-builder 1.4.2 tag with libglnx submodule (no wrap)

### Expected Behavior

Build succeeds

### Actual Behavior

Build fails because 1.4.2 (accidentally?) switched libglnx submodule to 5 years old version that doesn't support Meson

### Additional Information

This was already fixed through https://github.com/flatpak/flatpak-builder/commit/ae86bde81fbb0316f08121793c0824c18b1cfb9a but there is no tag containing the fix.

**Comment by TingPing** [comment]
Fixed in 1.4.3 release.
