### ISSUE TITLE
E: filters-but-no-output and E: gui-app-without-icon

### ISSUE THREAD

**Issue by wiiznokes** [flatpak/flatpak-builder#596]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.1

### Flatpak version

1.15.6

### How to reproduce

clone my repo: https://github.com/wiiznokes/fan-control.git, with the branch flatpak. This [is](https://github.com/wiiznokes/fan-control/blob/flatpak/resource/flatpak/com.wiiznokes.fan-control.json) my manifest.

Run this command:
```
flatpak-builder \
		--force-clean \
		--verbose \
		--ccache \
		packages \
		resource/flatpak/com.wiiznokes.fan-control.json
```

Note: this is the repo to PR to flathub: https://github.com/wiiznokes/flathub/tree/fan-control

### Expected Behavior

To build my flatpak app.

### Actual Behavior

It make this error:

```
    Finished release [optimized] target(s) in 1m 10s
Running: install -Dm644 ./resource/linux/com.wiiznokes.fan-control.png /app/share/icons/hicolor/128x128/apps/com.wiiznokes.fan-control.png
Running: install -Dm644 ./resource/linux/com.wiiznokes.fan-control.appdata.xml /app/share/metainfo/com.wiiznokes.fan-control.appdata.xml
Running: install -Dm644 ./resource/linux/com.wiiznokes.fan-control.desktop /app/share/applications/com.wiiznokes.fan-control.desktop
Running: install -Dm755 ./target/release/fan-control -t /app/bin/
compressing debuginfo in: /home/fedasus/Documents/fan-control/.flatpak-builder/rofiles/rofiles-zZ9uCg/files/bin/fan-control
processing: /home/fedasus/Documents/fan-control/.flatpak-builder/rofiles/rofiles-zZ9uCg/files/bin/fan-control
Nothing to do.
stripping /home/fedasus/Documents/fan-control/.flatpak-builder/rofiles/rofiles-zZ9uCg/files/bin/fan-control to /home/fedasus/Documents/fan-control/.flatpak-builder/rofiles/rofiles-zZ9uCg/files/lib/debug/bin/fan-control.debug
Committing stage build-fan-control to cache
Cleaning up
Renaming com.wiiznokes.fan-control.appdata.xml to share/metainfo/com.wiiznokes.fan-control.metainfo.xml
Running appstreamcli compose
Only accepting components: com.wiiznokes.fan-control, com.wiiznokes.fan-control.desktop
Processing directory: /home/fedasus/Documents/fan-control/.flatpak-builder/rofiles/rofiles-zZ9uCg/files
Composing metadata...
Run failed, some data was ignored.
Errors were raised during this compose run:
general
  E: filters-but-no-output

com.wiiznokes.fan-control
  E: gui-app-without-icon
Refer to the generated issue report data for details on the individual problems.
```

### Additional Information

This may be an error of mine but i checked multiple time and i don't think there is any error concerning my icons. And the error message is not very helpful so i choose to make a bug repport.

**Comment by bbhtt** [comment]
This is not an issue with flatpak-builder, it's coming from appstreamcli

The launchable value in the metainfo file is wrong https://github.com/wiiznokes/fan-control/blob/6725f1c08daf458fb95ae1e074ce81943c0101bb/resource/linux/com.wiiznokes.fan-control.metainfo.xml#L20

Your desktop file is `com.wiiznokes.fan-control.desktop` https://github.com/wiiznokes/fan-control/blob/flatpak/resource/linux/com.wiiznokes.fan-control.desktop
