### ISSUE TITLE
tar.gz Not Recognized as Gzip

### ISSUE THREAD

**Issue by clseibold** [flatpak/flatpak-builder#600]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.1

### Flatpak version

1.15.8

### How to reproduce

I'm using this archive as a source for a module: http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.4.tar.gz

### Expected Behavior

It should untar the archive

### Actual Behavior

I'm getting this error:
```
FB: Running: git config --get user.email
FB: Running: git config --get user.name
Emptying app dir 'build-dir'
FB: Running: flatpak info --arch=x86_64 --show-commit org.freedesktop.Sdk 23.08
FB: Running: flatpak info --show-location --arch=x86_64 org.freedesktop.Sdk 23.08
FB: Running: flatpak info --arch=x86_64 --show-commit org.freedesktop.Platform 23.08
Downloading sources
Starting build of us.to.scrollprotocol.Profectus
Cache miss, checking out last cache hit
FB: Mounting read-only fs: rofiles-fuse /home/clseibold/Dev/profectus/build-dir /home/clseibold/Dev/profectus/.flatpak-builder/rofiles/rofiles-l3eSJx
========================================================================
Building module sdl2-gfx in /home/clseibold/Dev/profectus/.flatpak-builder/build/sdl2-gfx-7
========================================================================
FB: Running: tar xf /home/clseibold/Dev/profectus/.flatpak-builder/downloads/8b5048f99c006f3d3e53d1a049576a789dec2f5683157e36849bbc5c878778fc/SDL2_gfx-1.0.4.tar.gz --no-same-owner --strip-components=0 -z

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: module sdl2-gfx: Child process exited with code 2
FB: Unmounting read-only fs: fusermount -uz /home/clseibold/Dev/profectus/.flatpak-builder/rofiles/rofiles-l3eSJx
```

### Additional Information

Here's the output of using the `file` command on the archive:
```
flatpaksources/SDL2_gfx-1.0.4.tar.gz: gzip compressed data, was "SDL2_gfx-1.0.4.tar", last modified: Sat Feb 24 05:36:39 2018, max compression, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 7728128
```

**Comment by TingPing** [comment]
The web server is broken, pick a different mirror or set `disable-http-decompression: true` on the source.

**Comment by clseibold** [comment]
> The server hosting it is broken

No it's not. I can download the file just fine in a browser. I believe the problem is that the tarfile was created on a Windows system.

**Comment by TingPing** [comment]
This project uses libcurl, your browser does not, they implement HTTP differently.

```
> curl -v https://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.4.tar.gz

...

< content-encoding: x-gzip

...
```

The server gives the wrong response. Another mirror works or enable the option to ignore the content-encoding.

**Comment by clseibold** [comment]
@TingPing It's a gzip file. What about the content encoding is incorrect?

**Comment by clseibold** [comment]
x-gzip is a valid content-encoding, it's just historical.

**Comment by clseibold** [comment]
> So what libcurl does is ungzip the tar.gz, so the download becomes just a tar but has the filename tar.gz. gzip then errors when run on the tar file.

Ok, thanks. Btw, this should have been the **very first** think you mention in your first response to this issue.

**Comment by TingPing** [comment]
Yes it's totally valid, curl respects it and ungzips the file.

I assume browsers just have a

```
if content_encoding == 'x-gzip' and filename.endswith('tar.gz'):
   # The server is probably wrong don't ungzip
```

I guess we could do similar.

**Comment by TingPing** [comment]
I was on my phone, sorry.

**Comment by clseibold** [comment]
Having that check would probably be useful in case this comes up again, and to create consistency between browsers and flatpak-builder. Anyways, I'll see if a mirror works.
