### ISSUE TITLE
No way to set `.flatpak-builder` dir

### ISSUE THREAD

**Issue by brunvonlope** [flatpak/flatpak-builder#606]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.3

### Flatpak version

1.14.4

### How to reproduce

1. Run appropriate flatpak-builder syntax to build some flatpak
2. `.flatpak-builder` dir is created always in the current dir

### Expected Behavior

Can set the path of .flatpak-builder dir (like I would do in a "traditional" build system, e.g. meson)

### Actual Behavior

.flatpak-builder dir is pervasively created in the current working dir without option to change it

**Comment by bbhtt** [comment]
```
flatpak-builder --help|grep .flatpak-builder

  flatpak-builder [OPTION…] DIRECTORY MANIFEST - Build manifest
  --state-dir=PATH                   Use this directory for state instead of .flatpak-builder
```

**Comment by brunvonlope** [comment]
Thanks 🫂
