### ISSUE TITLE
Inconsistent sha256sum after downloads

### ISSUE THREAD

**Issue by Pobega** [flatpak/flatpak-builder#607]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.1

### Flatpak version

1.15.8

### How to reproduce

Build https://github.com/flathub/com.fightcade.Fightcade, see that miniupnpc fails to validate the checksum. After replacing the checksum, it now fails to extract.

Note: the current head of the repo is https://github.com/flathub/com.fightcade.Fightcade/commit/1b05f1fd3d280d5ace617c1114c5c5794d3c80b7

### Expected Behavior

The checksum should be valid (verified using wget).

### Actual Behavior

The checksum is not valid, and the file does not extract properly with the 'new' checksum.

### Additional Information

miniupnpc has been in the build without changing for over a year, so I'm not sure exactly what changed to cause this issue.

**Comment by Pobega** [comment]
Looks like it may be something with `flatpak-builder` and that specific mirror. Switching to a [different mirror](https://github.com/flathub/com.fightcade.Fightcade/pull/134/commits/2e0c6b976216637522581ad200a9441e3db80b56) seems to have resolved the issue, at least locally.

I'm keeping this open since the issue is still reproducible and inconsistent with the results seen via a browser download or wget.

**Comment by TingPing** [comment]
The server they host it on is misconfigured.

```
> curl -v http://miniupnp.free.fr/files/miniupnpc-2.2.3.tar.gz
... 
< Content-Encoding: x-gzip
```

You can add the property `"disable-http-decompression": true` to the source.

**Comment by Pobega** [comment]
Thank you, I guess that solves the problem here! Appreciate the quick reply.
