### ISSUE TITLE
Allow running unit tests as part of build process

### ISSUE THREAD

**Issue by chergert** [flatpak/flatpak-builder#61]
Using `flatpak-builder` as part of a C-I process is incredibly convenient. It would be nice if I could force the build to fail when unit tests fail using an option like `"run-tests": true,` in the module description.

For make, this is generally going to be `check`, and for ninja this will generally be `test`.

One caveat though, is that we probably need network and display access if we're going to support things like appstream validation and initializing gtk as part of the test suite.

**Comment by chergert** [comment]
https://github.com/chergert/flatpak-builder/commit/dc86025fc5450970d0425b9caca825b49bf45cb2 provides a basic implementation, without the display/network access.

**Comment by alexlarsson** [comment]
I think this is interesting, but we need to take it a bit further:

 * We want to guarantee that the tests don't affect the result, so we want to run them with /app readonly.
 * Only run the tests if specified on the flatpak-builder commandline
 * Add more properties to tweak how to run tests. At the minimum we want test-commands, test-target, test-args (for allowing e.g. network access).

Optionally it would be nice to have a way for it to automatically set up a test environment with a session bus, a Xvfb (and whatever wayland has for it) and a dummy pulseaudio.

**Comment by alexlarsson** [comment]
One cool project would be to have Xvfb and pulsed an whatever host services in a flatpak app and then have it spawn that as a "fake" host and inject into the test run.

**Comment by alexlarsson** [comment]
See https://github.com/flatpak/flatpak-builder/pull/65
