### ISSUE TITLE
Support to install bundled assets when application's sources are extra-data

### ISSUE THREAD

**Issue by x80486** [flatpak/flatpak-builder#617]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Currently, there is no real path to include and install bundled assets when application's sources are `extra-data` — for instance: flathub/com.syntevo.SmartGit/pull/113

This is somehow counterintuitive to the packaging process because reusing application's assets should be the first option, rather than maintaining copies.

I suggest implementing a mechanism that allows developers to specify bundled assets in Flatpak manifest when application's sources are extra-data, which would be then installed alongside the application.

**Comment by bbhtt** [comment]
Flatpak builder supports it, see the note in https://docs.flatpak.org/en/latest/module-sources.html#extra-data

It's not allowed on Flathub specifically.

**Comment by x80486** [comment]
OK, then I guess I should move this one out to the `flathub` repository :sweat_smile:

**Comment by bbhtt** [comment]
We don't have any plans to support it, it was blocked specifically so that we can validate all the metadata.

**Comment by bbhtt** [comment]
And also the default appstreamcli compose command does not work when you place files ie. icon desktop and metainfo there
