### ISSUE TITLE
Renaming an applications id should add provides/id to appstream file

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak-builder#90]
If you rename foo.desktop and foo.appdata.xml to org.bar.Foo then it should label such in the appdata file so software can better show this.

```xml
<provides>
  <id>foo.desktop</id>
</provides>
```

**Comment by bilelmoussaoui** [comment]
We should also handle the case when we rename an appdata file, the id should be changed.

**Comment by TingPing** [comment]
It does do that.

**Comment by bilelmoussaoui** [comment]
Well, I just had an issue with Flathub a week or two back. Is it due to an old version of flatpak-builder?

**Comment by TingPing** [comment]
It isn't a new feature. You may have hit a bug, hard to guess.

**Comment by hfiguiere** [comment]
> It does do that.

It doesn't on a `rename-appdata-file`. Only on a `rename-dekstop-file`.

**Comment by hfiguiere** [comment]
Also the other condition is the `id` only changed if it matches the `rename-desktop-file` value.

Properly it should be changed if doesn't match the `id` of the package. This is what the PR is doing.
