### ISSUE TITLE
MAKEFLAGS / number of jobs

### ISSUE THREAD

**Issue by eszlari** [flatpak/flatpak-builder#91]
Why isn't MAKEFLAGS set to "-j \`nproc\`"? Is it, because there are supposedly (never experienced it myself) some projects that fail to compile and this could be hard to debug?

**Comment by eszlari** [comment]
I might add, that I'm taking about using "make" in a buildsystem = "simple" scenario.

**Comment by TingPing** [comment]
By default the build system implementations directly pass `-j ...` and the `no-parallel-make` property changes that. I agree it would be nice to expose this option via the `simple` build system somehow.

**Comment by TingPing** [comment]
> FLATPAK_MAKE_FLAGS

Well number of jobs isn't `make` specific so just `FLATPAK_BUILD_JOBS` containing a number could be used by any build system.

On a related note it would be nice for config opts to be in an env var to so you could do something like this:

```json
{
  "buildsystem": "simple",
  "config-opts": [
     "-a",
     "-lot",
     "-of",
     "-options"
  ],
  "build-commands": [
      "./a-strange-build-script --jobs=$FLATPAK_BUILD_JOBS $FLATPAK_CONFIG_OPTS"
  ]
```

Also is prefix exposed in an env var?

**Comment by alexlarsson** [comment]
Those all seems good to me. I'd love for anyone to add that.

For prefix, flatpak build always sets FLATPAK_DEST to the destination (which is typically /app, but not when e.g. building extensions).

**Comment by craigbarnes** [comment]
> Well number of jobs isn't `make` specific so just `FLATPAK_BUILD_JOBS` containing a number could be used by any build system.

`ninja` does parallel builds by default.

How about using something like `MAKEFLAGS=-j$(nproc)` by default and adding an option to the manifest format to disable it (per module)? Most makefiles generated by CMake and autotools should properly support parallel builds. Makefiles that are badly formed (or that deliberately don't support parallel builds) should really be marked as such in the makefile itself with [`.NOTPARALLEL:`].

[`.NOTPARALLEL`]: https://www.gnu.org/software/make/manual/make.html#index-_002eNOTPARALLEL

**Comment by alexlarsson** [comment]
This is now set as FLATPAK_BUILDER_N_JOBS
