### ISSUE TITLE
Flatpak Builder Packaging Issue

### ISSUE THREAD

**Issue by unkemptArc99** [flatpak/flatpak-builder#92]
Hi Guys!
Recently, I tried to build Polari from Builder (which uses flatpak-builder for it's build). I got this error -

````Error: module telepathy-glib: Failed to execute child process "eu-strip" (No such file or directory)````

I researched more about this and found that this is because I had no elfutils installed. Then, I came across - https://github.com/flatpak/flatpak/issues/648. Reading this, it felt that it might be an error in the packaging of flatpak-builder. 

My flatpak-builder version is 0.10.6. I'm using Linux Mint 18.1 Cinammon OS.

I think that this is a dependency issue for flatpak-builder, and elfutils should be installed during the installation of flatpak-builder.

**Comment by alexlarsson** [comment]
That seems like a packaging issue, yes, but the issue is with the mint package, not with flatpak-builder itself. You need to file it against the mint distribution.

**Comment by Wetrain** [comment]
Seems @farkass solution fixed this on Debian 9 for me.

**Comment by Maziak2520** [comment]
Issue still there
stripping flatpak/org.gnome.Evolution-stable/files/lib/libical.so.3.0.3 to flatpak/org.gnome.Evolution-stable/files/lib/debug/lib/libical.so.3.0.3.debug
Error: module libical: Failed to execute child process "eu-strip" (No such file or directory)

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

sudo flatpak-builder --force-clean org.gnome.Evolution-stable org.gnome.Evolution-stable.json
