### ISSUE TITLE
cmake should default to -DCMAKE_INSTALL_LIBDIR=lib

### ISSUE THREAD

**Issue by gcampax** [flatpak/flatpak-builder#93]
Otherwise cmake defaults to installing /app/lib64 on x86_64, which is incorrect for the GNOME and Freedesktop runtimes (probably all of them really)

**Comment by TingPing** [comment]
It is a bit of an opinionated change favoring the freedesktop runtime as another runtime could use `/app/lib64` which is probably OK but it shouldn't be hardcoded in `flatpak-builder` probably it should be patched in `cmake` in the runtime.

**Comment by alexlarsson** [comment]
I agree with @TingPing, the default for this should be up to the runtime.
Also, Is CMAKE_INSTALL_LIBDIR always available/used? I've had lots of issues with cmake properties not really being consistent among apps.

**Comment by TingPing** [comment]
As far as I can tell that is regularly used.

**Comment by gcampax** [comment]
CMAKE_INSTALL_LIBDIR comes from a module called GNUInstallDirs, which is part of the standard cmake modules (https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html ) so I assume it's always available, if not always honored?

Also I disagree that it's favoring the freedesktop runtime - simply because there is no other runtime at the moment, and it's only reasonable that a new runtime will follow the conventions established by freedesktop. We already decided eg that the app files live in /app or the configuration files live in /usr/etc .
But if this default can be selected in the runtime instead of flatpak-builder that's good too.

**Comment by alexlarsson** [comment]
The freedesktop runtime is the main used one, but there are also debian and fedora based ones in (less widespread so far) use, and these will use a different libdir. Enforcing a runtime-specific choice that will break these seems like a bad idea.

Basically, the freedesktop sdk should put a false in here: 
https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L223

We already do this for meson:
https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/meson-no-lib64.patch

**Comment by eszlari** [comment]
Do I miss something or why does lib64 show up again in my build after https://github.com/flathub/org.kde.krita/commit/70d55bde1f7819e27e74b52462f59d588f1d4f3a ?
