### ISSUE TITLE
Changing URL for source doesn't correctly invalidate cache.

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak-builder#96]
```diff
-          "url": "https://atom-installer.github.com/v1.23.1/atom-amd64.deb",
+          "url": "https://atom-installer.github.com/v1.23.2/atom-amd64.deb",
```

I imagine because the filename is identical.

**Comment by alexlarsson** [comment]
This is an archive source? Because it has:
```
builder_source_archive_checksum (BuilderSource  *source,
                                 BuilderCache   *cache,
                                 BuilderContext *context)
{
  BuilderSourceArchive *self = BUILDER_SOURCE_ARCHIVE (source);

  builder_cache_checksum_str (cache, self->url);
....
```

So, any change to the url should cause a rebuild...

**Comment by TingPing** [comment]
Yes an archive source. You are right it does trigger a rebuild but the new source is never attempted to be downloaded and the old download is used.

**Comment by alexlarsson** [comment]
Did the checksum change?

**Comment by TingPing** [comment]
I didn't change the checksum but the real checksum changed. I'd expect if the URL changed it would download it no matter what.

**Comment by alexlarsson** [comment]
Thats not how it works though. If a file exists with path $download/$sha1/$basename, it is assumed to be correct, otherwise we would re-download it each time we rebuilt that module. At any random build, how could we know that the file in the download cache was from a different uri?

**Comment by TingPing** [comment]
> how could we know that the file in the download cache was from a different uri?

`$download/$sha1/$encoded_url/$basename,` or such?

**Comment by alexlarsson** [comment]
I guess i explicitly chose not to do that, so we will not re-download a file if the file changed location but not contents (checksum).

**Comment by TingPing** [comment]
That is fair, I just think a lazy packager changing url but not checksum is probably more common than changing url to the same file. The the cost when either assumption is wrong is either a broken package or an extra download. So it is clear what side I would err on.

**Comment by alexlarsson** [comment]
Not sure which is right, but I don't think we want to change the download layout at this point.
